### DISCUSSION TITLE
Please write better docs

### DISCUSSION THREAD

**Discussion by jayson1200** [pytorch/torchtune#1045] [Ideas]
That is all

**Comment by RdoubleA** [comment]
Totally agree with the sentiment, we're constantly working to improve our docs :) anything in particular that frustrates you?

**Reply by GhostyGRM** [reply]
How about some examples of using custom datasets.

**Reply by RdoubleA** [reply]
Please see the documentation here: https://pytorch.org/torchtune/main/tutorials/datasets.html#custom-unstructured-text-corpus, especially the "custom" sections and "Local and remote datasets". Let me know if anything is still not clear.

For more visibility, we are planning an overhaul of our README to provide more quick examples and links to our docs.

**Reply by GhostyGRM** [reply]
Hi,

I’ve been trying to load my custom dataset from Hugging Face, which is in the ShareGPT conversational style, and convert it to the Llama2Chat format using Torchtune. However, I’m encountering some issues and it’s not working as expected.

From my understanding, Torchtune should handle the conversion from the ShareGPT format to the Llama2Chat format if the dataset is structured correctly. Do you have any code examples that demonstrate this process? I haven't been able to find any specific examples showing how to achieve this.

Thanks for your help!

**Reply by pbontrager** [reply]
If I'm understanding what you're trying to do correctly, you have a dataset in the sharegpt sytle and you want to use it with llama2 chat format? You should be able to do this:

```yaml
dataset:
    _component_: torchtune.datasets.chat_dataset
    source: hf/custom_dataset
    split: train
    conversation_style: sharegpt
    chat_format: torchtune.data.Llama2ChatFormat
```

Let me know if that helps.
