### DISCUSSION TITLE
Possible to fine tune on 2 different dataset classes?

### DISCUSSION THREAD

**Discussion by troy256** [pytorch/torchtune#1509] [Q&A] [answered]
I have a text_completion dataset that I've been fine tuning llama 3.1 on.  I now have another dataset I want to use, but it is for the "instruct" dataset class.  Is it possible to do a fine tuning run on both of these concurrently?  If not, is the best practice to train on 1st dataset and then train the resulting checkpoint files on the 2nd dataset?

**Comment by RdoubleA** [comment, marked as answer]
Hey @troy256, take a look at `torchtune.datasets._concat.ConcatDataset`, it does just what you described.

You can use it directly from the config for any recipe by specifying a list for your dataset:
```
dataset:
  - _component_: torchtune.datasets.instruct_dataset
    ...
  - _component_: torchtune.datasets.text_completion_dataset
```

Let us know if you run into any issues.

**Comment by troy256** [comment]
Thanks, I'm getting close.  My instruct dataset just has "prompt" and "response" columns (no "instruction").  I can't figure out which instruct template to use, or maybe I'm not specifying it correct.   I'd like to use an existing template instead of creating custom.

**Reply by RdoubleA** [reply]
We've just updated our APIs and will be updating our documentation very soon. If you use `torchtune.datasets.instruct_dataset` you don't need to specify any custom formatting as it will handle it for you, see here: https://github.com/pytorch/torchtune/blob/68d4f3ee1287ef60f3f17222ed7382fe5c33be96/torchtune/datasets/_instruct.py#L157

you just need to pass in `column_map = {"input": "prompt", "output": "response"}`. By default, it won't add any prompt template but it will format it correctly according to your dataset and it should be sufficient to start fine-tuning. Is there a specific prompt template you wanted to use?

**Comment by troy256** [comment]
Thanks.  What do I put for template in the dataset block?  It seems to require that:

`TypeError: instruct_dataset() missing 1 required keyword-only argument: 'template'`

Relevant yaml:
```
dataset:
  - _component_: torchtune.datasets.instruct_dataset
    source: /data/torchtune/dataset/instruct/parquet
    split: train
    train_on_input: True
    max_seq_len: 8192
    column_map: {"input": "prompt", "output": "response"}
  - _component_: torchtune.datasets.text_completion_dataset
    source: /data/torchtune/dataset/text_completion/parquet
    split: train
    max_seq_len: 8192
```

**Reply by RdoubleA** [reply]
ah, apologies this is confusing. our datasets have undergone a lot of changes recently. I would recommend [installing our nightlies](https://pytorch.org/torchtune/main/install.html#install-nightly-build) as this won't require you to pass in a prompt template. with the nightly build, your config should look like this, noticed that max_seq_len moved to the tokenizer:
```
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /tmp/Meta-Llama-3-8B-Instruct/original/tokenizer.model
  max_seq_len: 8192

dataset:
  - _component_: torchtune.datasets.instruct_dataset
    source: /data/torchtune/dataset/instruct/parquet
    split: train
    train_on_input: True
    column_map: {"input": "prompt", "output": "response"}
  - _component_: torchtune.datasets.text_completion_dataset
    source: /data/torchtune/dataset/text_completion/parquet
    split: train
```
