### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not str in collate fn

### ISSUE THREAD

**Issue by tambulkar** [pytorch/torchtune#1010]
Collate function arg `batch` expects `List[Dict[str, List[int]]` in the code but actually gets `List[Tuple[List[int],List[int]]]` at runtime.  My dataset config is 

```
dataset:
   _component_: torchtune.datasets.text_completion_dataset
  source: allenai/c4
  column: text
  max_seq_len: 2096
  data_dir: realnewslike
  split: train
```
