### ISSUE TITLE
Bug: 'txt' instead of 'text' for `text_completion_dataset`

### ISSUE THREAD

**Issue by SimiPixel** [pytorch/torchtune#1028]
In the tutorial on datasets (https://pytorch.org/torchtune/main/tutorials/datasets.html#custom-unstructured-text-corpus) both in the config and the code example the `source` keyword should be `text` and not `txt`

```yaml
# YAML config
dataset:
  _component_: torchtune.datasets.text_completion_dataset
  source: text 
  data_files: path/to/my_data.txt
```
