### ISSUE TITLE
GPTQ quantization not working with fine-tuned LLaMA3 models

### ISSUE THREAD

**Issue by sanchitintel** [pytorch/torchtune#1033]
### Problem Description

Hi,

#654 tried to enable GPTQ quantization with fine-tuned LLaMA2 models, but was closed.
I tried following a similar approach as that PR, but for fine-tuned LLaMA3 models.
It did not succeed because LLaMA3 uses the [`TikToken` tokenizer, whose `encode()` ](https://github.com/pytorch/torchtune/blob/main/torchtune/modules/tokenizers/_tiktoken.py#L230)has two more arguments than [this call to `encode()` in `torchao`](https://github.com/pytorch/ao/blob/main/torchao/_eval.py#L97). This wasn't an issue with LLaMA2, which used the `sentencepiece` tokenizer.

Thanks in advance for your help!

**Comment by sanchitintel** [comment]
@HDCharles would help fix it in `torchao` by making GPTQ compatible with TikToken. Thanks!

**Comment by sanchitintel** [comment]
Hi @RdoubleA, this issue still persists if LLaMA3 is first fine-tuned with LoRA, and then the output checkpoint is used to [quantize the model](https://pytorch.org/torchtune/main/tutorials/e2e_flow.html#speeding-up-generation-using-quantization) by running `tune run quantize --config ./custom_quantization_config.yaml`, which still crashes because `Int4WeightOnlyGPTQQuantizer` requires 2 positional inputs in its call to `quantize`.

If I port some changes from #654 in `torchtune/recipes/quantize.py`, and set the tokenizer to `torchtune.models.llama3.llama3_tokenizer`, I encounter a different error at https://github.com/EleutherAI/lm-evaluation-harness/blob/main/lm_eval/models/huggingface.py#L363:
```
'Llama3Tokenizer' object has no attribute 'bos_token_id'
```

 So, the `fine-tuning with LoRA -> quantization with GPTQ -> generation` path is not working for LLaMA3, as the quantization step fails. While I tried using CPU, CUDA users would also encounter the same error.

My yaml file for quantization has the following contents:
```
model:
  _component_: torchtune.models.llama3.llama3_8b

checkpointer:
  _component_:  torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: /localdisk/llama3_output
  checkpoint_files: [
    meta_model_0.pt
  ]
  recipe_checkpoint: null
  output_dir: /localdisk/llama3_output
  model_type: LLAMA3

device: cpu
dtype: bf16
seed: 1234

quantizer:
  _component_: torchtune.utils.quantization.Int4WeightOnlyGPTQQuantizer
  groupsize: 256

tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /localdisk/llama3/original/tokenizer.model
  ```
  

  
 Please advise as to how this issue could be resolved. I think it can be resolved by passing some example inputs to `quantize` at https://github.com/pytorch/torchtune/blob/main/recipes/quantize.py#L112 when `Int4WeightOnlyGPTQQuantizer` is used, but I'm not sure what example inputs we could provide, as #654 uses `torchao._models._eval.InputRecorder` to generate example inputs. 
 
 Thanks!
