### ISSUE TITLE
CUDA illegal memory access exception

### ISSUE THREAD

**Issue by l3utterfly** [pytorch/torchtune#1112]
My training crashes randomly with this error:
```
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /home/layla/src/pytorch/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xab (0x7c7abed98f2b in /home/layla/src/pytorch/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xd5 (0x7c7abed421c7 in /home/layla/src/pyt
orch/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x3f6 (0x7c7ac01b0af6 in /home/layla/src/pytorch/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x1c149 (0x7c7ac017e149 in /home/layla/src/pytorch/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x1dc25 (0x7c7ac017fc25 in /home/layla/src/pytorch/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x5405f4 (0x7c7abf3405f4 in /home/layla/src/pytorch/torch/lib/libtorch_python.so)
frame #6: c10::TensorImpl::~TensorImpl() + 0xd (0x7c7abed73cdd in /home/layla/src/pytorch/torch/lib/libc10.so)
frame #7: <unknown function> + 0x14a88b8 (0x7c7aac4a88b8 in /home/layla/src/pytorch/torch/lib/libtorch_cpu.so)
frame #8: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x13a (0x7c7aaff2378a in /home/layla/src/pytorch/torch/lib/libtorch_cpu.so)
frame #9: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x290 (0x7c7aaff1ba80 in /home/layla/src/pytorch/torch/lib/libtorch_cpu.so)
frame #10: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x78 (0x7c7abf5e7918 in /home/layla/src/pytorch/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0xd3e95 (0x7c7ac04f0e95 in /home/layla/miniconda3/envs/torchtune/bin/../lib/libstdc++.so.6)
frame #12: <unknown function> + 0x94ac3 (0x7c7ac1494ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #13: <unknown function> + 0x126850 (0x7c7ac1526850 in /lib/x86_64-linux-gnu/libc.so.6)
```

Using nightly build torchtune + latest pytorch (from git main branch)

**Comment by l3utterfly** [comment]
@ebsmothers This is the command I'm running: `tune run --nproc_per_node 6 full_finetune_distributed --config ./phi3.yaml`

I'll try `CUDA_LAUNCH_BLOCKING` thanks

**Comment by ebsmothers** [comment]
@l3utterfly sounds good, let me know what you find. Also, is your local `./phi3.yaml` file just a direct copy of the `phi3/mini_full.yaml` config, or have you made any other changes to it?

**Comment by l3utterfly** [comment]
@ebsmothers Here's my full config:
```
# Config for multi-device full finetuning in full_finetune_distributed.py
# using a Phi3 Mini 4K Instruct
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download microsoft/Phi-3-mini-4k-instruct --output-dir /tmp/Phi-3-mini-4k-instruct --hf-token <HF_TOKEN> --ignore-patterns ""
#
# Run this config on 4 GPUs using the following:
#  tune run --nproc_per_node 4 full_finetune_distributed --config phi3/mini_full
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run --nproc_per_node 4 full_finetune_distributed --config phi3/mini_full checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works best when the model is being fine-tuned on 2+ GPUs.
# Single device full finetuning requires more memory optimizations. It's
# best to use mini_low_memory.yaml for those cases

# Tokenizer
tokenizer:
  _component_: torchtune.models.phi3.phi3_mini_tokenizer
  path: /home/layla/src/text-generation-webui/models/Phi-3-mini-4k-instruct/tokenizer.model

# Dataset
dataset:
  _component_: torchtune.datasets.chat_dataset
  train_on_input: True
  source: json
  split: train[:20%]
  data_files: /home/layla/src/Layla-datasets/datasets_formatted/base-v5/train-phi3.jsonl
  conversation_style: sharegpt
  max_seq_len: 4096
  chat_format: torchtune.data.ChatMLFormat
seed: null
shuffle: False

# Model Arguments
model:
  _component_: torchtune.models.phi3.phi3_mini

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: /home/layla/src/text-generation-webui/models/Phi-3-mini-4k-instruct
  checkpoint_files: [
    model-00001-of-00002.safetensors,
    model-00002-of-00002.safetensors
  ]
  recipe_checkpoint: null
  output_dir: phi3-out
  model_type: PHI3_MINI
resume_from_checkpoint: False

# Fine-tuning arguments
batch_size: 2
epochs: 1
optimizer:
  _component_: torch.optim.AdamW
  lr: 5e-7
loss:
  _component_: torch.nn.CrossEntropyLoss
max_steps_per_epoch: null
gradient_accumulation_steps: 16

# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True
memory_efficient_fsdp_wrap: False

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: ${output_dir}
output_dir: phi3-out/log
log_every_n_steps: 1
```

Strang thing is running with `CUDA BLOCKING` the error does not happen anymore? Previously I can only get up to ~4 hours of training before it crashes, currently it's at 13 hours and continuing (but with a ~30% penalty on training speed due to the blocking config)
