### ISSUE TITLE
[config] have a single output_dir

### ISSUE THREAD

**Issue by felipemello1** [pytorch/torchtune#1265]
Currently our configs have:

```
output_dir: /tmp/alpaca-gemma-finetune
checkpointer:
  checkpoint_dir: /tmp/gemma-2b/
  output_dir: /tmp/gemma-2b

metric_logger:
  log_dir: ${output_dir}

```

Instead of creating 4 paths, we should have one path, and then build the others on top of it. eg:
```
output_dir: /tmp/gemma-2b-lora
checkpointer:
  checkpoint_dir: /tmp/${output_dir}/checkpoint/
  output_dir: /tmp/${output_dir}/checkpoint_output/

metric_logger:
  log_dir: /tmp/{output_dir}/metrics/
```

Also, we should probably rename checkpointer.output_dir to checkpointer.checkpoint_output_dir
