### ISSUE TITLE
Decouple dataset from prompt template

### ISSUE THREAD

**Issue by joecummings** [pytorch/torchtune#1343]
Right now if I want to use a Llama2 model with a custom dataset I have to tie that dataset directly to the Llama2 prompt template in code. I can't change it from the config. This means my experiments are incredibly hard to maintain. In addition, the prompt template from training should be used in inference and therefore I have to implement it again? Huge potential for silent bugs here.

In code:

```python
def custom_dataset(source, tokenizer, **kwargs):
    # The 'user' column is the input, and the 'code' column is the output.
    message_transform = InputOutputToMessages(
        train_on_input = False,
        column_map = {
            "input": "statement",
            "output": "code",
        }
    )

    prompt_template = Llama2PromptTemplate()

    # Build our dataset!
    return SFTDataset(
        source=source,
        message_transform=message_transform,
        model_transform=tokenizer,
        prompt_template=prompt_template,
        split=split,
    )
        
```

Ideally, I'd like to be able to do something like this in the config:

```yaml
dataset:
  _component_: path.to.custom_dataset
  prompt_template: torchtune.models.llama2.Llama2ChatTemplate
  split: sample
```

cc @RdoubleA

**Comment by pbontrager** [comment]
I agree it should be decoupled from the dataset so people can customize it. But I don't think it should be a dataset parameter at all, it should be part of the model_transform/tokenizer. So for Joe's example:

```yaml
model_transform:
  _component_: torchtune.models.llama3.llama3_tokenizer
  prompt_template: torchtune.models.llama2.Llama2ChatTemplate
  max_seq_len: 8192
  path: /tmp/llama3/tokenizer.model
```

This allows it to follow the model for eval and generate where you won't have the dataset.

[Off topic] I'm uncomfortable with the tokenizer truncating sequences. That feels like a dataset responsibility. I feel this could lead to unintuitive behavior during decoding.

**Comment by RdoubleA** [comment]
Good flagging this. This was possible in the old instruct/chat builders. I am currently working on revamping those with the new SFTDataset. In my mind the ideal behavior would be I can specify a custom prompt template directly from config or specify a string to an existing prompt template.

```
dataset:
  _component_: path.to.custom_dataset
  prompt_template: torchtune.models.llama2.Llama2ChatTemplate
  split: train
```
or
```
dataset:
  _component_: path.to.custom_dataset
  prompt_template:
    user:
    - "Question: "
    - " Answer: "
  split: train
```
this requires a lot of awkward type checking logic though
