### ISSUE TITLE
Can't do tune run with QWEN 2 model

### ISSUE THREAD

**Issue by dpalmasan** [pytorch/torchtune#1359]
I am trying to finetune and eval QWEN 2 model. If I run the recipe directly, running `LoRAFinetuneRecipeSingleDevice` everything works. However I when I try to run it through the CLI:

`tune run lora_finetune_single_device --config /data/users/dpalmasan/fbsource/fbcode/papaya/toolkit/experimental/llm_torchtune/config-qwen05-cpu.yml`

I am getting:

```
 File "/home/dpalmasan/local/miniconda3/lib/python3.12/site-packages/torchtune/config/_instantiate.py", line 20, in _create_component
    return _component_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpalmasan/local/miniconda3/lib/python3.12/site-packages/torchtune/utils/_checkpointing/_checkpointer.py", line 333, in __init__
    self._model_type = ModelType[model_type]
                       ~~~~~~~~~^^^^^^^^^^^^
  File "/home/dpalmasan/local/miniconda3/lib/python3.12/enum.py", line 814, in __getitem__
    return cls._member_map_[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'QWEN2'
```

Not sure why is this happening. My config file is:

```yaml
# Config for single device LoRA finetuning in lora_finetune_single_device.py
# using a Qwen2 0.5B model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download Qwen/Qwen2-0.5B-Instruct --output-dir /tmp/Qwen2-0.5B-Instruct --ignore-patterns None
#
# To launch on a single device, run the following command from root:
#   tune run lora_finetune_single_device --config qwen2/0.5B_lora_single_device
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run lora_finetune_single_device --config qwen2/0.5B_lora_single_device checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works only for training on single device.


# Model Arguments
model:
  _component_: torchtune.models.qwen2.lora_qwen2_0_5b
  lora_attn_modules: ['q_proj', 'k_proj', 'v_proj']
  apply_lora_to_mlp: False
  lora_rank: 32
  lora_alpha: 64

tokenizer:
  _component_: torchtune.models.qwen2.qwen2_tokenizer
  path: /tmp/qwen/Qwen2-0.5B-Instruct/vocab.json
  merges_file: /tmp/qwen/Qwen2-0.5B-Instruct/merges.txt

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: /tmp/qwen/Qwen2-0.5B-Instruct
  checkpoint_files: [
    model.safetensors
  ]
  recipe_checkpoint: null
  output_dir: /tmp/qwen/Qwen2-0.5B-Instruct-lora-finetune
  model_type: QWEN2

resume_from_checkpoint: False

# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.alpaca_cleaned_dataset
seed: null
shuffle: True
batch_size: 4

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  weight_decay: 0.01
  lr: 2e-3

lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torch.nn.CrossEntropyLoss

# Training
epochs: 1
max_steps_per_epoch: 50
gradient_accumulation_steps: 4
compile: False

# Logging
output_dir: /tmp/qwen/Qwen2-0.5B-Instruct-lora-finetune
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: ${output_dir}
log_every_n_steps: 1
log_peak_memory_stats: False

# Environment
device: cuda
dtype: bf16
enable_activation_checkpointing: True

# Show case the usage of pytorch profiler
# Set enabled to False as it's only needed for debugging training
profiler:
  _component_: torchtune.utils.setup_torch_profiler
  enabled: False

  #Output directory of trace artifacts
  output_dir: ${output_dir}/profiling_outputs

  #`torch.profiler.ProfilerActivity` types to trace
  cpu: True
  cuda: True

  #trace options passed to `torch.profiler.profile`
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False

  # `torch.profiler.schedule` options:
  # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
  wait_steps: 5
  warmup_steps: 5
  active_steps: 2
  num_cycles: 1

```
