### ISSUE TITLE
Error for inference LoRA Llama3-8b in Python Script

### ISSUE THREAD

**Issue by fangzhouli** [pytorch/torchtune#1387]
I have a finetuned LoRA-Llama3-8b model. Since I have many prompts, I would like to write a script to generate outputs for all prompts without repeatedly loading the model using the CLI script.

The following `generation_config.yaml` script for a single prompt worked for me:
```
model:
  _component_: torchtune.models.llama3.llama3_8b

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /to/my/tokenizer.model

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: /to/my/checkpoints/
  checkpoint_files: [
    meta_model_0.pt,
  ]
  output_dir: /to/my/checkpoints/
  model_type: LLAMA3
...
prompt: 'Tell me a joke.'
...
``` 

Here is my Python script for loading the state_dict:
```python
from torchtune.utils import FullModelTorchTuneCheckpointer
from torchtune.models.llama3 import llama3_8b

model = llama3_8b()
checkpointer = FullModelTorchTuneCheckpointer(
    checkpoint_dir="/to/my/checkpoints",
    checkpoint_files=["meta_model_0.pt"],
    output_dir="/to/my/checkpoints",
    model_type='LLAMA3',
)
ckpt_dict = checkpointer.load_checkpoint()
model_state_dict = ckpt_dict['model']
model.load_state_dict(model_state_dict)
```

This raises the following error:
```
RuntimeError: Error(s) in loading state_dict for TransformerDecoder:
        Missing key(s) in state_dict: "layers.0.sa_norm.scale", "layers.0.attn.q_proj.weight", "layers.0.attn.k_proj.weight", "layers.0.attn.v_proj.weight", "layers.0.attn.output_proj.weight", "layers.0.mlp_norm.scale", "layers.0.mlp.w1.weight", "layers.0.mlp.w2.weight", "layers.0.mlp.w3.weight", "layers.1.sa_norm.scale", "layers.1.attn.q_proj.weight", "layers.1.attn.k_proj.weight", "layers.1.attn.v_proj.weight", "layers.1.attn.output_proj.weight", ...
        Unexpected key(s) in state_dict: "layers.0.attention_norm.weight", "layers.0.attention.wq.weight", "layers.0.attention.wk.weight", "layers.0.attention.wv.weight", ...
```
