### ISSUE TITLE
RuntimeError: CUDA error: named symbol not found

### ISSUE THREAD

**Issue by MaxwelsDonc** [pytorch/torchtune#1521]
when I run the quantized model `tune run generate --config ./custom_quantization_generation_config.yaml`, I encountered a different problem:

```
RuntimeError: CUDA error: named symbol not found
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
I'm not sure what is causing this error. I also tried generating tokens with the original model, and it works fine. Below are my environment details and the custom_quantization_generation_config.yaml file.

| **Property**            | **Value**                                   |
|-------------------------|---------------------------------------------|
| PyTorch Version          | 2.4.1+cu121                                 |
|torchtune       |         0.2.1             |
| CUDA Available           | True                                        |
| GPU Name                 | Tesla V100-SXM2-32GB                        |
| nvcc                     | NVIDIA (R) Cuda compiler driver             |
| Copyright                | (c) 2005-2023 NVIDIA Corporation            |
| Built on                 | Tue_Feb__7_19:32:13_PST_2023                |
| Cuda compilation tools   | release 12.1, V12.1.66                      |
| Build                    | cuda_12.1.r12.1/compiler.32415258_0         |
| NVIDIA-SMI |535.54.03   |       
| Driver Version| 535.54.03   |
| CUDA Version| 12.2 |

```
# Config for running the InferenceRecipe in generate.py to generate output from an LLM
#
# To launch, run the following command from root torchtune directory:
#    tune run generate --config generation

# Model arguments
model:
  _component_: torchtune.models.llama3.llama3_8b

checkpointer:
  _component_: torchtune.utils.FullModelTorchTuneCheckpointer
  checkpoint_dir: Llama3-Gen
  checkpoint_files: [
    meta_model_0-4w.pt
  ]
  output_dir: Llama3-Gen
  model_type: LLAMA3

device: cuda
dtype: bf16

seed: 1234

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: Meta-Llama-3-8B/original/tokenizer.model

# Generation arguments; defaults taken from gpt-fast
prompt: "Tell me a joke?"
instruct_template: null
chat_format: null
max_new_tokens: 300
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300
# It is recommended to set enable_kv_cache=False for long-context models like Llama3.1
enable_kv_cache: True

quantizer:
  _component_: torchtune.utils.quantization.Int4WeightOnlyQuantizer
  groupsize: 256
```
