### ISSUE TITLE
Generate Command phi3 Error

### ISSUE THREAD

**Issue by sgupta1007** [pytorch/torchtune#1581]
I have used  command  t`une run generate --config custom_quantization.yaml prompt='Explain some topic'`

Config custom_quantization.yaml
```
model:
  _component_: torchtune.models.phi3.qlora_phi3_mini

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: //fine_tuned_phi/
  checkpoint_files: [
    hf_model_0001_0.pt,hf_model_0002_0.pt,adapter_0.pt
  ]
  model_type: PHI3
  output_dir: /fine_tuned_legal_phi/

device: cuda
dtype: bf16
seed: 1234

quantizer:
  _component_: torchtune.utils.quantization.Int4WeightOnlyQuantizer
  groupsize: 256

```

Error Flagged 
KeyError: 'PHI3``

**Comment by sgupta1007** [comment]
How to generate inference using  phi3 finetune model fine tune through  qlora

**Comment by felipemello1** [comment]
I believe it should be "model_type: PHI3_MINI"

https://github.com/pytorch/torchtune/blob/4fbe7b2d4956b3790c51d7a255c0040cf5c38fad/recipes/configs/phi3/mini_lora.yaml#L46

**Comment by sgupta1007** [comment]
model type change resolved this error but lead to `FullModelHFCheckpointer.load_checkpoint() got an unexpected keyword argument 'weights_only'` error

**Comment by felipemello1** [comment]
@joecummings , have you seen this before?

**Comment by sgupta1007** [comment]
I am not able to use generate without quantization.

I will try to explain my approach for generation :

```
1. Perform phi3 qlora finetuning on 1 epoch
2. Supply the adapter and models weights to checkpointer files in config file 
3. Keep the model component as torchtune.models.phi3.qlora_phi3_mini. 
4. Run Generation Command tune run generate --config custom_quantization.yaml prompt='Explain some topic'
```

**Comment by apthagowda97** [comment]
@sgupta1007  as adapter is already merged why we need to give adapter and model weights??

**Comment by apthagowda97** [comment]
```
model:
  _component_: torchtune.models.llama3_1.llama3_1_8b

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: /path/output/
  checkpoint_files: [
    hf_model_0001_0.pt,
    hf_model_0002_0.pt,
    hf_model_0003_0.pt,
    hf_model_0004_0.pt
  ]
  output_dir: /path/output/
  model_type: LLAMA3

device: cuda
dtype: bf16

seed: 1234

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /path/llama3.1-8b/original/tokenizer.model

# Generation arguments; defaults taken from gpt-fast
prompt: "Tell me a joke?"
instruct_template: null
chat_format: null
max_new_tokens: 300
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300
# It is recommended to set enable_kv_cache=False for long-context models like Llama3.1
enable_kv_cache: True

quantizer: null
```

I am getting CUDA out of Memory on this in A100 GPU for 8 bn model ... strange!!!
