### ISSUE TITLE
Garbled output after lora finetune on alpaca

### ISSUE THREAD

**Issue by shawnricecake** [pytorch/torchtune#1641]
Hi,

I adopt the lora finetune for LLaMA-3.1-8B on the default alpaca clean dataset.

Then, I use the `generate.py` and `generation.yaml` for the test.

I found there is garbled output after lora fine-tune.

Can anyone help?

**Comment by ebsmothers** [comment]
Hi @shawnricecake thanks for creating the issue. Can you share the configs you used for both the LoRA finetune and the generation, as well as the output you observed?

**Comment by shawnricecake** [comment]
> Hi @shawnricecake thanks for creating the issue. Can you share the configs you used for both the LoRA finetune and the generation, as well as the output you observed?

Hi,

The lora config is the following:
```

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /path/to/Meta-Llama-3.1-8B-Instruct/original/tokenizer.model
  max_seq_len: 8192

# Model Arguments
model:
  _component_: torchtune.models.llama3_1.lora_llama3_1_8b
  lora_attn_modules: ['q_proj', 'v_proj']
  apply_lora_to_mlp: False
  apply_lora_to_output: False
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.0

checkpointer:
  _component_: torchtune.training.FullModelMetaCheckpointer
  checkpoint_dir: /path/to/Meta-Llama-3.1-8B-Instruct/original/
  checkpoint_files: [
    consolidated.00.pth
  ]
  recipe_checkpoint: null
  output_dir: /path/to/output
  model_type: LLAMA3
resume_from_checkpoint: False
save_adapter_weights_only: False

# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.alpaca_cleaned_dataset
seed: null
shuffle: True
batch_size: 1

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  fused: True
  weight_decay: 0.01
  lr: 3e-4
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss

# Training
epochs: 1
max_steps_per_epoch: null
gradient_accumulation_steps: 32

# Logging
output_dir: /path/to/logs/
metric_logger:
  _component_: torchtune.training.metric_logging.WandBLogger
  log_dir: ${output_dir}
log_every_n_steps: 1
log_peak_memory_stats: False

# Environment
device: cuda
dtype: bf16
enable_activation_checkpointing: False
```

and the generation config:
```
model:
  _component_: torchtune.models.llama3_1.llama3_1_8b

checkpointer:
  _component_: torchtune.training.FullModelMetaCheckpointer
  checkpoint_dir: /path/to/lora_output/
  checkpoint_files: [
    meta_model_0.pt
  ]
  output_dir: /tmp/log/
  model_type: LLAMA3-1-8B

device: cuda
dtype: bf16

seed: 1234

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /path/to/Meta-Llama-3.1-8B-Instruct/original/tokenizer.model
  max_seq_len: null

# Generation arguments; defaults taken from gpt-fast
prompt: "Tell me a joke?"
instruct_template: null
chat_format: null
max_new_tokens: 300
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300

enable_kv_cache: True

quantizer: null
```
