### ISSUE TITLE
How can I used the fine-tuned model for inferencing?

### ISSUE THREAD

**Issue by himanshushukla12** [pytorch/torchtune#1699]
So when I did fine-tuning of a llama3, my configuration file looks like:
```
# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ~/meta-llama/Meta-Llama-3-8B-Instruct/original/tokenizer.model
  max_seq_len: null

# Model Arguments
model:
  _component_: torchtune.models.llama3.lora_llama3_8b
  lora_attn_modules: ['q_proj', 'v_proj', 'k_proj', 'output_proj']
  apply_lora_to_mlp: False
  apply_lora_to_output: False
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.0

checkpointer:
  _component_: torchtune.training.FullModelMetaCheckpointer
  checkpoint_dir: ~/meta-llama/Meta-Llama-3-8B-Instruct/original/
  checkpoint_files: [
    consolidated.00.pth
  ]
  recipe_checkpoint: null
  output_dir: ~/meta-llama/Meta-Llama-3-8B-Instruct-alcapa-trained/
  model_type: LLAMA3
resume_from_checkpoint: False
save_adapter_weights_only: False

# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.alpaca_cleaned_dataset
seed: null
shuffle: True
batch_size: 4

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  weight_decay: 0.01
  lr: 3e-4
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss

# Training
epochs: 1
max_steps_per_epoch: null
gradient_accumulation_steps: 32

# Logging
output_dir: ~/meta-llama/lora_finetune_output
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}
log_every_n_steps: 1
log_peak_memory_stats: False

# Environment
device: cuda
dtype: bf16
enable_activation_checkpointing: False

```

Now I want to know how I can used when the model gets fine-tuned, also after fine tuning, I got two files in directory
```
~/meta-llama/Meta-Llama-3-8B-Instruct-alcapa-trained/
- adapter_0.pt
- meta_model_0.pt
```

Just tell me how can I use my fine-tuned model for inferencing, also this is what my generation fine named `custom_generation_config.yaml` looks:
```
model:
  _component_: torchtune.models.llama3.llama3_8b


checkpointer:
  _component_: torchtune.training.FullModelMetaCheckpointer
  checkpoint_dir: ~/meta-llama/Meta-Llama-3-8B-Instruct-alcapa-trained/
  checkpoint_files: [
    # adapter_0.pt,
    meta_model_0.pt
  ]
  output_dir: ~/meta-llama/Meta-Llama-3-8B-Instruct/
  model_type: LLAMA3

device: cuda
dtype: bf16

seed: 1234

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ~/meta-llama/Meta-Llama-3-8B-Instruct/original/tokenizer.model
  max_seq_len: null

# Generation arguments; defaults taken from gpt-fast
prompt: "Tell me a joke?"
instruct_template: null
chat_format: null
max_new_tokens: 300
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300
# It is recommended to set enable_kv_cache=False for long-context models like Llama3.1
enable_kv_cache: True

quantizer: null
```

and I'm running the inferencing using the syntax below in my terminal:
``
tune run generate --config ./custom_generation_config.yaml prompt="Hello, my name is"
``
