### ISSUE TITLE
using Torchtune to teach LLMs a new language

### ISSUE THREAD

**Issue by almugabo** [pytorch/torchtune#1859]
I am trying to full fine tune Llama3.2-1b to "teach" it another language (via continous pretraining). 
he idea is to have a model, which, given a prompt in a language  , it continues the sentences in that language. 
I am using a dataset of about 25 Million words. 

When I use Unsloth for Qlora finetuning a 4bit model, after 3 epochs, the model performs how I would expect it. 
(I give a prompt in that language and get as response new text in the language which makes sense. 

However, when using Torchtune (with text completion dataset), even after 5 epochs the results are not what I would expect. 
It just continue in English or outputs non-sensical sentences. 
P.S: the loss also behaves funny. it goes down, then up then down almost erratic (downtrends). 

My question is : 
what I am doing wrong ? 

Below is my configuration file:

```yaml 
    
#Model and checkpointing 

xpath_model_chkp: './CPT_Llama/LLama_32_1b/_Torchtune/_model'
xpath_model_logs: './CPT_Llama/LLama_32_1b/_Torchtune/_model_logs'
xpath_dataset: './_datasets/monolingual_train.json'

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ${xpath_model_chkp}/original/tokenizer.model
  max_seq_len: 2048

# Dataset
dataset:
  _component_: torchtune.datasets.text_completion_dataset
  source: json
  data_files: ${xpath_dataset}
  column: text
  split: train

seed: null
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.llama3_2.llama3_2_1b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ${xpath_model_chkp}
  checkpoint_files: [
    model.safetensors
  ]
  recipe_checkpoint: null
  output_dir: ${xpath_model_chkp}
  model_type: LLAMA3_2
resume_from_checkpoint: False

# Fine-tuning arguments
batch_size: 4
epochs: 5
optimizer:
  _component_: bitsandbytes.optim.PagedAdamW8bit
  lr: 2e-5
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
max_steps_per_epoch: null #10  ## for testing, otherwise set to null
gradient_accumulation_steps: 1
optimizer_in_bwd: True
compile: True #False # set it to True for better memory and performance

# Training environment
device: cuda

# Memory management
enable_activation_checkpointing: True

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${xpath_model_logs}
output_dir: ${xpath_model_logs}
log_every_n_steps: 1
log_peak_memory_stats: False
```
