### ISSUE TITLE
LoRA enabling question?

### ISSUE THREAD

**Issue by kailashg26** [pytorch/torchtune#1935]
Hi I'm running LLaMA 3.1 on single device and wanted to run with LoRA. 

But when I check the yaml file, I see something like this: (8B_lora_single_device.yaml)

```
model:
  _component_: torchtune.models.llama3_1.lora_llama3_1_8b
  lora_attn_modules: ['q_proj', 'v_proj']
  apply_lora_to_mlp: False
  apply_lora_to_output: False
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.0
```
Does that mean LoRA is disabled if both these knobs are False?

```
apply_lora_to_mlp: False
apply_lora_to_output: False
```
