### ISSUE TITLE
TypeError: BuilderConfig.__init__() got an unexpected keyword argument 'template'

### ISSUE THREAD

**Issue by jinz2014** [pytorch/torchtune#1997]
[rank]:   File "/home/envs/rocm6.2/lib/python3.10/site-packages/datasets/builder.py", line 582, in _create_builder_config
[rank]:     builder_config = self.BUILDER_CONFIG_CLASS(**config_kwargs)
[rank]: TypeError: BuilderConfig.__init__() got an unexpected keyword argument 'template'

The "template" is found in the yaml file:

```
dataset:
  _component_: torchtune.datasets.instruct_dataset
  column_map:
    #dialogue: document
    input: document
    output: summary
  source: EdinburghNLP/xsum
  split: train[:2000]
  template: torchtune.data.SummarizeTemplate
  train_on_input: false
  trust_remote_code: true
```

**Comment by RdoubleA** [comment]
Hey @jinz2014, you may be referring to an old version of the documentation for how to set up an instruct dataset. This was refactored in a past release and prompt templates are now specified in the tokenizer. Please see https://pytorch.org/torchtune/main/basics/instruct_datasets.html for an example of how to set it up.

For your case, you would specify it like so:

```
tokenizer:
  # replace with your actual tokenizer
  _component_: torchtune.models.gemma.gemma_tokenizer
  prompt_template: torchtune.data.SummarizeTemplate
  
dataset:
  _component_: torchtune.datasets.instruct_dataset
  column_map:
    input: document
    output: summary
  source: EdinburghNLP/xsum
  split: train[:2000]
  train_on_input: false
  trust_remote_code: true
```
