### ISSUE TITLE
Fine tuning on custom dataset with custom prompt template

### ISSUE THREAD

**Issue by GLorenzo679** [pytorch/torchtune#2004]
I'm trying to fine tune a model (llama 3.1 8B Instruct) on a custom dataset.
The dataset is made of 3 fields: input, metadata and output. I could use the Alpaca style prompt, but I don't think it fits my use case.
Looking at the documentation I didn't find  a clear explanation on how to do this.
I managed to have a working setup by creating this custom dataset builder, as suggested in the doc:

```python
from typing import Any, Mapping

from torchtune.data import Message
from torchtune.datasets import SFTDataset
from torchtune.modules.transforms import Transform


class CustomMessageTransform(Transform):
    def __call__(self, sample: Mapping[str, Any]) -> Mapping[str, Any]:
        messages = [
            Message(
                role="system",
                content="You are an AI assistant helping a user translate a law into code using the Catala programming language. You are provided with a law paragraph and metadata, including useful user-defined constructs. Your task is to generate the code in the Catala programming language.",
                masked=True,
                eot=True,
            ),
            Message(
                role="user",
                content=f"###INPUT###\n{sample['input']}\n###METADATA###\n{sample['metadata']}",
                masked=True,
                eot=True,
            ),
            Message(
                role="assistant",
                content=sample["output"],
                masked=False,
                eot=True,
            ),
        ]
        return {"messages": messages}


def custom_dataset(tokenizer, **load_dataset_kwargs) -> SFTDataset:
    message_transform = CustomMessageTransform()

    return SFTDataset(
        model_transform=tokenizer,
        message_transform=message_transform,
        **load_dataset_kwargs,
    )
```

This is my custom config:

```yaml
model_dir: "./models/llama3.1-8B-Instruct"
logs_dir: "./logs/llama3.1-8B-Instruct"
dataset_dir: "./dataset/dataset.json"

# Model Arguments
model:
  _component_: torchtune.models.llama3_1.lora_llama3_1_8b
  lora_attn_modules: ["q_proj", "v_proj"]
  apply_lora_to_mlp: False
  apply_lora_to_output: False
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.0

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ${model_dir}/original/tokenizer.model
  max_seq_len: 8192

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ${model_dir}
  checkpoint_files:
    [
      model-00001-of-00004.safetensors,
      model-00002-of-00004.safetensors,
      model-00003-of-00004.safetensors,
      model-00004-of-00004.safetensors,
    ]
  recipe_checkpoint: null
  output_dir: ${model_dir}
  model_type: LLAMA3
resume_from_checkpoint: False
save_adapter_weights_only: False

# Dataset and Sampler
dataset:
  _component_: src.finetune.torchtune.format_dataset.custom_dataset
  source: json
  data_files: ${dataset_dir}
  split: train
seed: null
shuffle: True
batch_size: 2

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  fused: True
  weight_decay: 0.01
  lr: 3e-4
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss

# Training
epochs: 3
max_steps_per_epoch: null
gradient_accumulation_steps: 4
compile: True # set it to True for better memory and performance

# Logging
output_dir: ${logs_dir}/lora_finetune_output
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${logs_dir}
log_every_n_steps: 5
log_peak_memory_stats: False

# Environment
device: cuda
dtype: bf16

# Activations Memory
enable_activation_checkpointing: True
enable_activation_offloading: False

# Profiler (disabled)
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False

  #Output directory of trace artifacts
  output_dir: ${logs_dir}/profiling_outputs

  #`torch.profiler.ProfilerActivity` types to trace
  cpu: True
  cuda: True

  #trace options passed to `torch.profiler.profile`
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False

  # `torch.profiler.schedule` options:
  # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
  wait_steps: 5
  warmup_steps: 5
  active_steps: 2
  num_cycles: 1
```

(The custom configuration works only if I prepend "PYTHONPATH=${pwd}:PYTHONPATH" to the tune run command).
Is it necessary to add "train_on_input=True" even if I masked my system and user prompt? What is the difference between setting train_on_input to True/False and masking Messages as I did?

Am I doing this the right way? Would it be possible to add more examples about this type of task in the documentation?
