### ISSUE TITLE
[Clean up] Use `FormattedFiles` in configs

### ISSUE THREAD

**Issue by joecummings** [pytorch/torchtune#2073]
Any configs in which `checkpoint_files` is a list of files > 4, use FormattedFiles utility to shrink the size of the file. 

Example from [llama3/70B_lora](https://github.com/pytorch/torchtune/blob/main/recipes/configs/llama3/70B_lora.yaml)
Current file:
```yaml
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir:  /tmp/Meta-Llama-3-70B-Instruct
  checkpoint_files: [
    model-00001-of-00030.safetensors,
    model-00002-of-00030.safetensors,
    model-00003-of-00030.safetensors,
    model-00004-of-00030.safetensors,
    model-00005-of-00030.safetensors,
    model-00006-of-00030.safetensors,
    model-00007-of-00030.safetensors,
    model-00008-of-00030.safetensors,
    model-00009-of-00030.safetensors,
    model-00010-of-00030.safetensors,
    model-00011-of-00030.safetensors,
    model-00012-of-00030.safetensors,
    model-00013-of-00030.safetensors,
    model-00014-of-00030.safetensors,
    model-00015-of-00030.safetensors,
    model-00016-of-00030.safetensors,
    model-00017-of-00030.safetensors,
    model-00018-of-00030.safetensors,
    model-00019-of-00030.safetensors,
    model-00020-of-00030.safetensors,
    model-00021-of-00030.safetensors,
    model-00022-of-00030.safetensors,
    model-00023-of-00030.safetensors,
    model-00024-of-00030.safetensors,
    model-00025-of-00030.safetensors,
    model-00026-of-00030.safetensors,
    model-00027-of-00030.safetensors,
    model-00028-of-00030.safetensors,
    model-00029-of-00030.safetensors,
    model-00030-of-00030.safetensors,
  ]
  recipe_checkpoint: null
  output_dir: /tmp/Meta-Llama-3-70B-Instruct
  model_type: LLAMA3
```

What it should be:
```yaml
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir:  /tmp/Meta-Llama-3-70B-Instruct
  checkpoint_files: 
    filename_format: model-{}-of-{}.safetensors
    max_filename: 00030
  recipe_checkpoint: null
  output_dir: /tmp/Meta-Llama-3-70B-Instruct
  model_type: LLAMA3
```

How you should test:
```
tune run --nproc-per-node 2 lora_finetune_distributed --config llama3/70B_lora
```
Paste the output in your PR to confirm that it runs!
