### ISSUE TITLE
knowledge_distillation_distributed Qwen2.5 14B to 3B, but vocal_size is not same

### ISSUE THREAD

**Issue by mathCrazyy** [pytorch/torchtune#2119]
RuntimeError: The size of tensor a (152064) must match the size of tensor b (151936) at non-singleton dimension 1,
Qwen7B, 14B the vocal_size is 152064, for qwen3B the vocab_size is 151936.
what should I do , thanks for your reply.

**Comment by joecummings** [comment]
Yep, this makes sense as the vocab sizes are slightly different! When I inspect the vocab files for Qwen2.5 14B and Qwen2.5 3B, I see that actually all the tokens up to 151664 are exactly the same. 

My guess is that the different vocab sizes are to help with a more efficient attention calculation, but don't quote me on that. Since these extra tokens are just padding and should never really be predicted, you should be able to modify the knowledge distillation recipe to drop the extra 128 tokens before calculating the loss between the teacher and the parent. Then the dimensions should line up and everything should work fine!

1. `tune cp knowledge_distillation_single_device .`
2. After [L638](https://github.com/pytorch/torchtune/blob/5eb04cd934ad84efff61e5dbf7a054fd7af184ec/recipes/knowledge_distillation_single_device.py#L638), you can do something like this:
```python
for _, i in enumerate(teacher_logits):
	teacher_logits[i] = teacher_logits[i][:, :, :151936]
```
We have to loop over the logits b/c the default cross entropy loss is performed in chunks to reduce memory spikes. 
3. `tune run knowledge_distillation_single_device.py --config path/to/your/config.yaml`

cc @lindawangg as the expert in knowledge distillation here

**Comment by joecummings** [comment]
Alright you really piqued my interest with this one so I setup a ridiculous KD run with Qwen2.5 32B into Qwen2.5 0.5B. Here's my config:

```yaml
# Tokenizer for everything?!?!?
tokenizer:
  _component_: torchtune.models.qwen2_5.qwen2_5_tokenizer
  path: /tmp/Qwen2.5-0.5B-Instruct/vocab.json
  merges_file: /tmp/Qwen2.5-0.5B-Instruct/merges.txt
  max_seq_len: null

# Student model
model:
  _component_: torchtune.models.qwen2.lora_qwen2_0_5b
  lora_attn_modules: ['q_proj', 'k_proj', 'v_proj']
  apply_lora_to_mlp: False
  lora_rank: 32
  lora_alpha: 64

# Student checkpointer
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Qwen2.5-0.5B-Instruct
  checkpoint_files: [model.safetensors]
  recipe_checkpoint: null
  output_dir: /tmp/Qwen2.5-0.5B-Instruct-finetune
  model_type: QWEN2
resume_from_checkpoint: False

# Teacher model
teacher_model:
  _component_: torchtune.models.qwen2_5.qwen2_5_32b_instruct

# Teacher checkpointer
teacher_checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Qwen2.5-32B-Instruct
  checkpoint_files:
    filename_format: model-{}-of-{}.safetensors
    max_filename: "00017"
  recipe_checkpoint: null
  output_dir: ./
  model_type: QWEN2

# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.alpaca_cleaned_dataset
  packed: False  # True increases speed
seed: 123
shuffle: True
batch_size: 2

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  weight_decay: 0.01
  lr: 3e-4
lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

# Losses
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
kd_loss:
  _component_: torchtune.modules.loss.ForwardKLWithChunkedOutputLoss
kd_ratio: 0.5

# Training
epochs: 1
max_steps_per_epoch: null
compile: False  # pytorch compile, set to true for better perf/memory
gradient_accumulation_steps: 8  # Use to increase virtual batch size

# Logging
output_dir: /tmp/qwen_kd
metric_logger:
  _component_: torchtune.training.metric_logging.WandBLogger
  project: kd-32b-into-0.5
log_every_n_steps: 1
log_peak_memory_stats: True

# Environment
device: cuda
dtype: bf16
enable_activation_checkpointing: False  # True reduces memory
```

And some initial logs from Weights & Biases:
<img width="1360" alt="Screenshot 2024-12-06 at 12 42 38 PM" src="https://github.com/user-attachments/assets/05691429-c6b0-4f19-b364-cf6917a9230e">


I am running this on 4 A100s. 

Interestingly, I see that we instantiate a single tokenizer for the KD recipe. For 90% of the use-cases this is fine (and even in this one really), b/c most model families use the same tokenizer anyways. However, for maximum flexibility we should use the teacher tokenizer for the teacher model and the student tokenizer for the student model. This will add a little more memory overhead, but worth it in my opinion. cc @lindawangg  and @ebsmothers for their thoughts.
