### ISSUE TITLE
How to retrieve the distilled model in a manner similar to the OpenAI API interface ?

### ISSUE THREAD

**Issue by lingq1** [pytorch/torchtune#2148]
I used the script `tune run --nnodes 1 --nproc_per_node 2 knowledge_distillation_distributed --config llama3_2/8B_to_1B_KD_lora_distributed` to distill the model and saved the results to `/tmp/torchtune/llama3_2_8B_to_1B/KD_lora_distributed`. How can I run my 1B model in a way similar to the OpenAI API to verify its effectiveness?

**Comment by joecummings** [comment]
Congrats on the successful fine-tune @lingq1!

There are a couple ways to determine effectiveness of your model.
1. **Benchmarks** - These are standardized datasets where the output from your model is compared against the desired output for a given task. Some common benchmarks include [MMMU](https://mmmu-benchmark.github.io/), which collects subsets of knowledge from science, anthropology, algebra, etc and asks models a series of multiple choice questions to see how close it gets to the right answer. The advantage of benchmarks is they are easy to compare against other model's performances. The disadvantage is that they can be fairly easy to game, so the longer a benchmark is around the less useful it tends to be.
2. **Vibes** - Another popular way of measuring the effectiveness of your model is just to play around with it for awhile! Ask it some questions, try to stump it, see what interesting behavior emerges. 
![LLM_Eval](https://github.com/user-attachments/assets/24bdd241-a1cc-4790-b210-231f22d4c0c3)

I believe that both approaches are important to determining if your fine-tuned model is "good". So how can you implement these methods in torchtune?

For benchmarking, torchtune provides an integration with the [EleutherAI Eval Harness](https://github.com/EleutherAI/lm-evaluation-harness/tree/main). Simply create a config similar to the following example:

```yaml
# Model Arguments
model:
  _component_: torchtune.models.llama3_2.llama3_2_1b

# Checkpointer
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/torchtune/llama3_2_8B_to_1B/KD_lora_distributed/epoch_X # substitute with your final epoch number
  checkpoint_files: [model.safetensors]
  output_dir: ./ # Not needed
  model_type: LLAMA3_2

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /tmp/torchtune/llama3_2_8B_to_1B/KD_lora_distributed/base_model/original/tokenizer.model

# Environment
device: cuda
dtype: bf16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed

# EleutherAI specific eval args
tasks: ["truthfulqa_mc2"]
limit: null
max_seq_length: 4096
batch_size: 8
enable_kv_cache: True

# Quantization specific args
quantizer: null
```

And run this config with `tune run eleuther_eval --config PATH/TO/YOUR/CONFIG.YAML`

Now for playing around with the model, you have some options. torchtune provides a generation script that works OOTB; however, it is very simple and only lets your use a set prompt to receive some output - there is no chat functionality.

```yaml
# Model Arguments
model:
  _component_: torchtune.models.llama3_2.llama3_2_1b

# Checkpointer
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/torchtune/llama3_2_8B_to_1B/KD_lora_distributed/epoch_X # substitute with your final epoch number
  checkpoint_files: [model.safetensors]
  output_dir: ./ # Not needed
  model_type: LLAMA3_2

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /tmp/torchtune/llama3_2_8B_to_1B/KD_lora_distributed/base_model/original/tokenizer.model
device: cuda
dtype: bf16

seed: 1234

# Generation arguments; defaults taken from gpt-fast
prompt:
  system: null
  user: "Tell me a joke."
max_new_tokens: 300
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300

enable_kv_cache: True

quantizer: null
```

And launch with `tune run generate --config PATH/TO/YOUR/CONFIG.YAML`

However, thanks to some awesome work from @felipemello1, it's also really easy to chat with your model through torchtune's integration with [vLLM](https://docs.vllm.ai/en/latest/index.html)!! Follow [the steps outlined in this PR description](https://github.com/pytorch/torchtune/pull/2074) to get started. Once you have everything setup you can run vLLM locally:

```python
from vllm import LLM, SamplingParams

def print_outputs(outputs):
    for output in outputs:
        prompt = output.prompt
        generated_text = output.outputs[0].text
        print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
    print("-" * 80)

llm = LLM(
    model="/tmp/torchtune/llama3_2_8B_to_1B/KD_lora_distributed/epoch_X", # substitute with your final epoch number
    load_format="safetensors",
    kv_cache_dtype="auto",
)
sampling_params = SamplingParams(max_tokens=16, temperature=0.5)

conversation = [
    {"role": "system", "content": "You are a helpful assistant"},
    {"role": "user", "content": "Hello"},
    {"role": "assistant", "content": "Hello! How can I assist you today?"},
    {
        "role": "user",
        "content": "Write an essay about the importance of higher education.",
    },
]
outputs = llm.chat(conversation, sampling_params=sampling_params, use_tqdm=False)
print_outputs(outputs)
```

Lastly, I know you mentioned that OpenAI API compatible evaluation ... this probably isn't the fastest way to get things up and running, but because torchtune integrates with vLLM and vLLM provides a similar interface, this is totally possible! You can read more on setting this up [here](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html?ref=blog.mozilla.ai).

Feel free to post some results when you're done evaluating!
