### ISSUE TITLE
Very bad convergence with bf16

### ISSUE THREAD

**Issue by EugenHotaj** [pytorch/torchtune#2254]
We've noticed very bad convergence when training in `bf16` vs `fp32`. 

As a comparison, here are the loss curves between `bf16`:
<img width="540" alt="Screenshot 2025-01-11 at 2 07 33 PM" src="https://github.com/user-attachments/assets/13bae6af-f264-4b6d-aa8d-81690f7e4fca" />

and `fp32`:
<img width="539" alt="Screenshot 2025-01-11 at 2 08 40 PM" src="https://github.com/user-attachments/assets/25713594-31c9-4faf-98b2-32d270100fa7" />

The training runs are identical besides the `dtype`. Notice that even after 250 steps the `bf16` run does not go below `0.7` loss. In theory, it should be possible to get similar convergence rates with either `dtype` (at least I think there are multiple existence proofs inside Meta 😛). 

One thing I tried doing was setting FSDP's [`reduce_dtype=fp32` ](https://github.com/pytorch/pytorch/blob/main/torch/distributed/fsdp/_fully_shard/_fsdp_api.py#L28) (had to hardcode because torchtune doesn't expose this option AFAICT) but it did not seem to help much. Any other options we should be looking into?

Need to confirm this but I think one thing that would greatly help is to keep optimizer states in `fp32`. It would use a lot more memory than end-to-end `bf16` but at least it would not slow down training as much as doing everything in `fp32`. Is there an easy way to do this in torchtune/pytorch? Would doing something like below work?

```
model = create_model(dtype=fp32)
optimizer(model.parameters())
model.to(bf16)
```

**Comment by felipemello1** [comment]
Hey @EugenHotaj, thanks for flagging this! I can take a look at it this week. To unblock you, if you have time, can you run it with bf16 and try NOT compiling the loss? You can comment it out in the recipe or set compile = false (but that also disables it for the model)

I have a vague memory of someone saying that that CE + compile skips upcasting to fp32.

if you are motivated, please double check that we do logits.float() inside of the loss call (i am on a plane, internet is not letting me check that)

**Comment by EugenHotaj** [comment]
@felipemello1 thanks for taking a look! I'm not using compile right now, just running the default [llama3_1 config](https://github.com/pytorch/torchtune/blob/main/recipes/configs/llama3_1/8B_full.yaml)  with a different dataset. I could try turning on compile (with the change you suggested) to see if it makes a difference.

**Comment by EugenHotaj** [comment]
Compile (skipping the loss) didn't seem to help

**Comment by EugenHotaj** [comment]
I tried manually hacking the Adam optimizer to keep moments in `fp32` but didn't help unfortunately. 

One thing I discovered is that FSDP2 allows you to keep your weights in `fp32` and do the compute in `bf16` ([here](https://github.com/pytorch/pytorch/blob/334ee8ba40fcd4d29fed14bddf553a035d1fea87/torch/distributed/fsdp/_fully_shard/_fsdp_api.py#L22-L27) -- might be good to expose these params in the torchtune config btw). Good news is that training is basically as fast as using `bf16` again now, but we're still using 2x the memory unfortunately.

**Comment by EugenHotaj** [comment]
@felipemello1 any luck on this?

**Comment by felipemello1** [comment]
hey @EugenHotaj , just got time to start it today. 

- I am running it now to reproduce the pattern using on single device
- Then I will take a look if there is some quick win related to the loss
- Then I will try to reproduce it on HF

If it doesnt happen in HF, we know its a torchtune issue. If it happens there, then I wonder if our premise is correct that bf16 convergence == fp32 convergence

**Comment by felipemello1** [comment]
Single device llama 3b, no difference. Bf16 actually seems better

![Image](https://github.com/user-attachments/assets/ad4815b4-2072-44ac-8e66-e3c21d5a26f1)

```
tune run full_finetune_single_device --config llama3_2/3B_full_single_device enable_activation_checkpointing=True enable_activation_offloading=True compile=False dataset.packed=True dataset.split=train[:5%] tokenizer.max_seq_len=1024 metric_logger=torchtune.training.metric_logging.WandBLogger metric_logger.project=profiling log_every_n_steps=1 log_peak_memory_stats=True gradient_accumulation_steps=1 max_steps_per_epoch=50 epochs=1 batch_size=1 profiler.enabled=False optimizer_in_bwd=True optimizer=torch.optim.AdamW dtype=fp32
```

gonna try to reproduce it using distributed

**Comment by EugenHotaj** [comment]
@felipemello1 one thing I would test is setting `gas > 0`. I think what might be happening is that we lose precision when accumulating gradients.

**Comment by felipemello1** [comment]
For distributed, no large changes. Let me take a look at grad accumulation

![Image](https://github.com/user-attachments/assets/0fd1afce-c67a-490e-9ec0-d4b97ec7537c)

```
tune run --nproc_per_node 8 full_finetune_distributed --config llama3_2/3B_full enable_activation_checkpointing=True enable_activation_offloading=True compile=False dataset.packed=True dataset.split=train[:5%] tokenizer.max_seq_len=1024 metric_logger=torchtune.training.metric_logging.WandBLogger metric_logger.project=profiling log_every_n_steps=1 log_peak_memory_stats=True gradient_accumulation_steps=1 max_steps_per_epoch=50 epochs=1 batch_size=1 profiler.enabled=False optimizer_in_bwd=True optimizer=torch.optim.AdamW dtype=fp32
```

**Comment by felipemello1** [comment]
used single_device, grad_acc=4, bsz=1, nothing crazy :/

![Image](https://github.com/user-attachments/assets/d5cb14f5-4fff-4ce0-94f4-0bb65154870e)

```
tune run full_finetune_single_device --config llama3_2/3B_full_single_device enable_activation_checkpointing=True enable_activation_offloading=True compile=False dataset.packed=True dataset.split=train[:5%] tokenizer.max_seq_len=1024 metric_logger=torchtune.training.metric_logging.WandBLogger metric_logger.project=profiling log_every_n_steps=1 log_peak_memory_stats=True gradient_accumulation_steps=4 max_steps_per_epoch=30 epochs=1 batch_size=1 profiler.enabled=False optimizer_in_bwd=False optimizer=torch.optim.AdamW dtype=fp32
```

**Comment by felipemello1** [comment]
can you reproduce it with some public dataset and share the config with me? I can test it with 8xA100

**Comment by EugenHotaj** [comment]
Hmm that's definitely surprising. Are you able to try with the following config (but your own dataset):
* Maybe the issue is not as prevalent for 3b model 
* Maybe 2e-5 LR is too high
* Let it run for longer, say 100-200 steps.

Also dumb q but how are you testing bf16 on A100s?

```
name: ???
output_dir: /traindata/eugen/runs/torchtune/${name}

# Dataset Arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /traindata/llama_hf_ckpt/Llama-3.1-8B-Instruct/original/tokenizer.model
  max_seq_len: 131072

dataset: <your-ds>
  
seed: 42
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.llama3_1.llama3_1_8b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /traindata/llama_hf_ckpt/Llama-3.1-8B-Instruct/
  checkpoint_files: [
    model-00001-of-00004.safetensors,
    model-00002-of-00004.safetensors,
    model-00003-of-00004.safetensors,
    model-00004-of-00004.safetensors
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA3
resume_from_checkpoint: False

# Fine-tuning arguments
batch_size: 1
epochs: 1

optimizer:
  _component_: torch.optim.Adam
  lr: 6e-7
  fused: True
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
max_steps_per_epoch: 230
compile: False  # torch.compile the model + loss, True increases speed + decreases memory
optimizer_in_bwd: False  # True saves memory. Requires gradient_accumulation_steps=1
gradient_accumulation_steps: 8  # Use to increase effective batch size
clip_grad_norm: 1.0

# Training env
device: cuda
dtype: bf16

# Memory management
enable_activation_checkpointing: True  # True reduces memory
enable_activation_offloading: False  # True reduces memory
custom_sharded_layers: ['tok_embeddings', 'output']  # Layers to shard separately (useful for large vocab size models). Lower Memory, but lower speed.

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.WandBLogger
  project: torchtune
  name: ${name}
  log_dir: ${output_dir}/logs
log_every_n_steps: 1
log_peak_memory_stats: True
```
