### ISSUE TITLE
`torch._inductor.exc.LoweringException: NoValidChoicesError` using torch 2.6.0

### ISSUE THREAD

**Issue by nathan-az** [pytorch/torchtune#2392]
### Error

```
[rank0]:     raise NoValidChoicesError(
[rank0]: torch._inductor.exc.LoweringException: NoValidChoicesError: No choices to select, please consider adding ATEN into max_autotune_gemm_backends config (defined in torch/_inductor/config.py) to allow at least one choice. 
[rank0]:   target: flex_attention_backward
```

I encounter the above issue using `tune run --nproc_per_node 4 full_finetune_distributed --config configs/llama3_1_8b.yaml` on 4x L40S GPUs.

* `torchtune` is installed from `main`. 
* `torch` is 2.6.0 from `pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel`
* `torchao` is the most recent release on pypi

It appears to be related to the flex attention backward step. I'm not sure why it's not caught during compilation but I frankly don't have much knowledge of how flex attention works.

The error appears to fix when dropping to `pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel`.

Curious if this is a known issue, or I've done anything obviously wrong?

### Config
<details>

```yaml
# set automatically
output_dir: /workspace/shared/outputs/llama3_1_8B/full_fsdp_offload # /tmp may be deleted by your system. Change it to your preference.

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /workspace/shared/base_models/Meta-Llama-3.1-8B-Instruct/original/tokenizer.model
  max_seq_len: 2048

# Dataset
dataset:
  _component_: torchtune.datasets.alpaca_dataset
  packed: True  # True increases speed
seed: null
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.llama3_1.llama3_1_8b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer

  # checkpoint_dir set automatically
  checkpoint_dir: /workspace/shared/base_models/Meta-Llama-3.1-8B-Instruct/
  checkpoint_files:
    filename_format: model-{}-of-{}.safetensors

    # ensure you set `max_filename` based on your model's number of files
    max_filename: '00004'
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA3
resume_from_checkpoint: False

# Fine-tuning arguments
batch_size: 1
gradient_accumulation_steps: 4
epochs: 1

optimizer:
  _component_: torch.optim.AdamW
  lr: 2e-5
  fused: False
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
max_steps_per_epoch: 4
clip_grad_norm: 1.0
compile: True  # torch.compile the model + loss, True increases speed + decreases memory
optimizer_in_bwd: False  # True saves memory. Requires gradient_accumulation_steps=1

# Training env
device: cuda

# Memory management
fsdp_cpu_offload: False
enable_activation_checkpointing: True  # True reduces memory
enable_activation_offloading: False  # True reduces memory
custom_sharded_layers: ['tok_embeddings', 'output']  # Layers to shard separately (useful for large vocab size models). Lower Memory, but lower speed.

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}/logs
log_every_n_steps: 1
log_peak_memory_stats: False


# Profiler
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False

  #Output directory of trace artifacts
  output_dir: ${output_dir}/profiling_outputs

  #`torch.profiler.ProfilerActivity` types to trace
  cpu: True
  cuda: True

  #trace options passed to `torch.profiler.profile`
  profile_memory: True
  with_stack: False
  record_shapes: True
  with_flops: True

  # `torch.profiler.schedule` options:
  # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
  wait_steps: 5
  warmup_steps: 3
  active_steps: 2
  num_cycles: 1
```

</details>

### Full stacktrace:

<details>

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/shared/torchtune_custom/recipes/full_finetune_distributed.py", line 1024, in <module>
[rank0]:     sys.exit(recipe_main())
[rank0]:              ^^^^^^^^^^^^^
[rank0]:   File "/workspace/shared/torchtune_custom/torchtune/config/_parse.py", line 99, in wrapper
[rank0]:     sys.exit(recipe_main(conf))
[rank0]:              ^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/shared/torchtune_custom/recipes/full_finetune_distributed.py", line 1019, in recipe_main
[rank0]:     recipe.train()
[rank0]:   File "/workspace/shared/torchtune_custom/recipes/full_finetune_distributed.py", line 890, in train
[rank0]:     current_loss.backward()
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_tensor.py", line 626, in backward
[rank0]:     torch.autograd.backward(
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/autograd/__init__.py", line 347, in backward
[rank0]:     _engine_run_backward(
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/autograd/graph.py", line 823, in _engine_run_backward
[rank0]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/autograd/function.py", line 307, in apply
[rank0]:     return user_fn(self, *args)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1710, in backward
[rank0]:     return impl_fn()
[rank0]:            ^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1700, in impl_fn
[rank0]:     out = CompiledFunction._backward_impl(ctx, all_args)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 2037, in _backward_impl
[rank0]:     CompiledFunction.compiled_bw = aot_config.bw_compiler(
[rank0]:                                    ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 489, in __call__
[rank0]:     return self.compiler_fn(gm, example_inputs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/backends/common.py", line 54, in _wrapped_bw_compiler
[rank0]:     return disable(disable(bw_compiler_fn)(*args, **kwargs))
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 745, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_utils_internal.py", line 95, in wrapper_function
[rank0]:     return function(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1808, in bw_compiler
[rank0]:     return inner_compile(
[rank0]:            ^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 569, in compile_fx_inner
[rank0]:     return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/repro/after_aot.py", line 102, in debug_wrapper
[rank0]:     inner_compiled_fn = compiler_fn(gm, example_inputs)
[rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 675, in _compile_fx_inner
[rank0]:     mb_compiled_graph = fx_codegen_and_compile(
[rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1129, in fx_codegen_and_compile
[rank0]:     return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 979, in codegen_and_compile
[rank0]:     graph.run(*example_inputs)
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/graph.py", line 855, in run
[rank0]:     return super().run(*args)
[rank0]:            ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/fx/interpreter.py", line 167, in run
[rank0]:     self.env[node] = self.run_node(node)
[rank0]:                      ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1496, in run_node
[rank0]:     result = super().run_node(n)
[rank0]:              ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/fx/interpreter.py", line 230, in run_node
[rank0]:     return getattr(self, n.op)(n.target, args, kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1143, in call_function
[rank0]:     raise LoweringException(e, target, args, kwargs).with_traceback(
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1133, in call_function
[rank0]:     out = lowerings[target](*args, **kwargs)  # type: ignore[index]
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/lowering.py", line 409, in wrapped
[rank0]:     out = decomp_fn(*args, **kwargs)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/kernel/flex_attention.py", line 2361, in flex_attention_backward
[rank0]:     broadcasted_grad_key = autotune_select_algorithm(
[rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/select_algorithm.py", line 1909, in autotune_select_algorithm
[rank0]:     return _ALGORITHM_SELECTOR_CACHE(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/select_algorithm.py", line 1379, in __call__
[rank0]:     raise NoValidChoicesError(
[rank0]: torch._inductor.exc.LoweringException: NoValidChoicesError: No choices to select, please consider adding ATEN into max_autotune_gemm_backends config (defined in torch/_inductor/config.py) to allow at least one choice. 
[rank0]:   target: flex_attention_backward
[rank0]:   args[0]: TensorBox(StorageBox(
[rank0]:     InputBuffer(name='primals_1', layout=FixedLayout('cuda:0', torch.bfloat16, size=[1, 32, 2048, 128], stride=[4096, 128, 4096, 1]))
[rank0]:   ))
[rank0]:   args[1]: TensorBox(StorageBox(
[rank0]:     InputBuffer(name='primals_2', layout=FixedLayout('cuda:0', torch.bfloat16, size=[1, 32, 2048, 128], stride=[8388608, 262144, 128, 1]))
[rank0]:   ))
[rank0]:   args[2]: TensorBox(StorageBox(
[rank0]:     InputBuffer(name='primals_3', layout=FixedLayout('cuda:0', torch.bfloat16, size=[1, 32, 2048, 128], stride=[8388608, 262144, 128, 1]))
[rank0]:   ))
[rank0]:   args[3]: TensorBox(StorageBox(
[rank0]:     InputBuffer(name='getitem', layout=FixedLayout('cuda:0', torch.bfloat16, size=[1, 32, 2048, 128], stride=[8388608, 128, 4096, 1]))
[rank0]:   ))
[rank0]:   args[4]: TensorBox(StorageBox(
[rank0]:     DonatedBuffer(name='getitem_1', layout=FixedLayout('cuda:0', torch.float32, size=[1, 32, 2048], stride=[65536, 2048, 1]))
[rank0]:   ))
[rank0]:   args[5]: TensorBox(StorageBox(
[rank0]:     InputBuffer(name='tangents_1', layout=FixedLayout('cuda:0', torch.bfloat16, size=[1, 32, 2048, 128], stride=[8388608, 262144, 128, 1]))
[rank0]:   ))
[rank0]:   args[6]: TensorBox(StorageBox(
[rank0]:     Pointwise(
[rank0]:       'cuda',
[rank0]:       torch.float32,
[rank0]:       def inner_fn(index):
[rank0]:           _, i1, i2 = index
[rank0]:           tmp0 = ops.constant(0, torch.float32)
[rank0]:           return tmp0
[rank0]:       ,
[rank0]:       ranges=[1, 32, 2048],
[rank0]:       origin_node=full_default,
[rank0]:       origins=OrderedSet([full_default])
[rank0]:     )
[rank0]:   ))
[rank0]:   args[7]: Subgraph(name='fw_graph0', graph_module=<lambda>(), graph=None)
[rank0]:   args[8]: Subgraph(name='joint_graph0', graph_module=<lambda>(), graph=None)
[rank0]:   args[9]: (2048, 2048, TensorBox(StorageBox(
[rank0]:     InputBuffer(name='primals_5', layout=FixedLayout('cuda:0', torch.int32, size=[1, 1, 16], stride=[16, 16, 1]))
[rank0]:   )), TensorBox(StorageBox(
[rank0]:     InputBuffer(name='primals_4', layout=FixedLayout('cuda:0', torch.int32, size=[1, 1, 16, 16], stride=[256, 256, 16, 1]))
[rank0]:   )), TensorBox(StorageBox(
[rank0]:     InputBuffer(name='primals_7', layout=FixedLayout('cuda:0', torch.int32, size=[1, 1, 16], stride=[16, 16, 1]))
[rank0]:   )), TensorBox(StorageBox(
[rank0]:     InputBuffer(name='primals_8', layout=FixedLayout('cuda:0', torch.int32, size=[1, 1, 16, 16], stride=[256, 256, 16, 1]))
[rank0]:   )), TensorBox(StorageBox(
[rank0]:     InputBuffer(name='primals_9', layout=FixedLayout('cuda:0', torch.int32, size=[1, 1, 16], stride=[16, 16, 1]))
[rank0]:   )), TensorBox(StorageBox(
[rank0]:     InputBuffer(name='primals_10', layout=FixedLayout('cuda:0', torch.int32, size=[1, 1, 16, 16], stride=[256, 256, 16, 1]))
[rank0]:   )), TensorBox(StorageBox(
[rank0]:     InputBuffer(name='primals_11', layout=FixedLayout('cuda:0', torch.int32, size=[1, 1, 16], stride=[16, 16, 1]))
[rank0]:   )), TensorBox(StorageBox(
[rank0]:     InputBuffer(name='primals_12', layout=FixedLayout('cuda:0', torch.int32, size=[1, 1, 16, 16], stride=[256, 256, 16, 1]))
[rank0]:   )), 128, 128, Subgraph(name='mask_graph0', graph_module=<lambda>(), graph=None))
[rank0]:   args[10]: 0.08838834764831843
[rank0]:   args[11]: {'PRESCALE_QK': False, 'ROWS_GUARANTEED_SAFE': False, 'BLOCKS_ARE_CONTIGUOUS': False, 'OUTPUT_LOGSUMEXP': True}
[rank0]:   args[12]: ()
[rank0]:   args[13]: (TensorBox(StorageBox(
[rank0]:     InputBuffer(name='primals_6', layout=FixedLayout('cuda:0', torch.int64, size=[1, 2048], stride=[2048, 1]))
[rank0]:   )),
```

</details>
