### ISSUE TITLE
TensorBoard logging error with Llama 3.3 70b

### ISSUE THREAD

**Issue by timrbula** [pytorch/torchtune#2430]
I see this error in the logs after each step when LORA tuning Llama 3.3 70b with TensorBoard as the metric logger. This same config works just fine with the Qwen 2.5 models. Thanks for any help!

```
RuntimeError: .numpy() is not supported for tensor subclasses.
```

Environment:

```
torch==2.7.0.dev20250207+cu124
torchtune==0.5.0
tensorboard==2.19.0
```

Full stack trace
```
[rank0]: File "/opt/conda/lib/python3.12/site-packages/recipes/lora_finetune_distributed.py", line 933, in <module>
[rank0]: sys.exit(recipe_main())
[rank0]: ^^^^^^^^^^^^^
[rank0]: File "/opt/conda/lib/python3.12/site-packages/torchtune/config/_parse.py", line 99, in wrapper
[rank0]: sys.exit(recipe_main(conf))
[rank0]: ^^^^^^^^^^^^^^^^^
[rank0]: File "/opt/conda/lib/python3.12/site-packages/recipes/lora_finetune_distributed.py", line 928, in recipe_main
[rank0]: recipe.train()
[rank0]: File "/opt/conda/lib/python3.12/site-packages/recipes/lora_finetune_distributed.py", line 866, in train
[rank0]: self._metric_logger.log_dict(
[rank0]: File "/opt/conda/lib/python3.12/site-packages/torchtune/training/metric_logging.py", line 311, in log_dict
[rank0]: self.log(name, data, step)
[rank0]: File "/opt/conda/lib/python3.12/site-packages/torchtune/training/metric_logging.py", line 307, in log
[rank0]: self._writer.add_scalar(name, data, global_step=step, new_style=True)
[rank0]: File "/opt/conda/lib/python3.12/site-packages/torch/utils/tensorboard/writer.py", line 378, in add_scalar
[rank0]: summary = scalar(
[rank0]: ^^^^^^^
[rank0]: File "/opt/conda/lib/python3.12/site-packages/torch/utils/tensorboard/summary.py", line 371, in scalar
[rank0]: tensor = make_np(tensor).squeeze()
[rank0]: ^^^^^^^^^^^^^^^
[rank0]: File "/opt/conda/lib/python3.12/site-packages/torch/utils/tensorboard/_convert_np.py", line 23, in make_np
[rank0]: return _prepare_pytorch(x)
[rank0]: ^^^^^^^^^^^^^^^^^^^
[rank0]: File "/opt/conda/lib/python3.12/site-packages/torch/utils/tensorboard/_convert_np.py", line 32, in _prepare_pytorch
[rank0]: x = x.detach().cpu().numpy()
[rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: .numpy() is not supported for tensor subclasses.
```

Torchtune config

```yaml
batch_size: 2
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/models/meta-llama/Llama-3.3-70B-Instruct/
  checkpoint_files:
    filename_format: model-{}-of-{}.safetensors
    max_filename: '00030'
  model_type: LLAMA3
  output_dir: /tmp/custom_models/llama33_70b-lora
  recipe_checkpoint: null
clip_grad_norm: 5
compile: true
custom_sharded_layers:
- tok_embeddings
- output
dataset:
  _component_: torchtune.datasets.chat_dataset
  conversation_column: conversations
  conversation_style: openai
  data_files: /tmp/datasets/conversation.jsonl
  new_system_prompt: null
  packed: false
  source: json
  split: train
  train_on_input: false
device: cuda
dtype: bf16
enable_activation_checkpointing: true
enable_activation_offloading: true
epochs: 3
exp_name: llama33_70b-lora
fsdp_cpu_offload: false
gradient_accumulation_steps: 1
log_every_n_steps: 1
log_peak_memory_stats: true
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 5
max_steps_per_epoch: null
metric_logger:
  _component_: torchtune.training.metric_logging.TensorBoardLogger
  log_dir: /tmp/custom_models/llama33_70b-lora/logs
  organize_logs: true
model:
  _component_: torchtune.models.llama3_3.lora_llama3_3_70b
  apply_lora_to_mlp: true
  apply_lora_to_output: false
  lora_alpha: 32
  lora_attn_modules:
  - q_proj
  - v_proj
  - output_proj
  lora_dropout: 0.0
  lora_rank: 32
optimizer:
  _component_: torchao.prototype.low_bit_optim.AdamW8bit
  lr: 1.0e-05
  weight_decay: 0.01
optimizer_in_bwd: false
output_dir: /tmp/llama33_70b-lora
profiler:
  _component_: torchtune.training.setup_torch_profiler
  active_steps: 2
  cpu: true
  cuda: true
  enabled: false
  num_cycles: 1
  output_dir: /tmp/custom_models/llama33_70b-lora/profiling_outputs
  profile_memory: true
  record_shapes: true
  wait_steps: 5
  warmup_steps: 3
  with_flops: false
  with_stack: false
resume_from_checkpoint: false
run: 0
save_adapter_weights_only: true
seed: 42
shuffle: true
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  max_seq_len: 32768
  path: /tmp/models/Llama-3.3-70B-Instruct/original/tokenizer.model
```
