### ISSUE TITLE
resume full fine-tuning from a previous checkpoint

### ISSUE THREAD

**Issue by agunapal** [pytorch/torchtune#2455]
Running into issues when I try to resume training from  a certain epoch

Specifying the following config complains that the output and checkpoint dir are the same
```
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/torchtune/llama_guard_3_8B/full/
  checkpoint_files: [
    model-00001-of-00004.safetensors,
    model-00002-of-00004.safetensors,
    model-00003-of-00004.safetensors,
    model-00004-of-00004.safetensors
  ]
  recipe_checkpoint: /tmp/torchtune/llama_guard_3_8B/full/recipe_state/recipe_state.pt
  output_dir: ${output_dir}
  model_type: LLAMA3
resume_from_checkpoint: True
```

If I point the checkpont_dir to `/tmp/torchtune/llama_guard_3_8B/full/epoch_4`, then it ends up looking for the checkpoint in `/tmp/torchtune/llama_guard_3_8B/full`

```
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/torchtune/llama_guard_3_8B/full/epoch_4/
  checkpoint_files: [
    model-00001-of-00004.safetensors,
    model-00002-of-00004.safetensors,
    model-00003-of-00004.safetensors,
    model-00004-of-00004.safetensors
  ]
  recipe_checkpoint: /tmp/torchtune/llama_guard_3_8B/full/recipe_state/recipe_state.pt
  output_dir: ${output_dir}
  model_type: LLAMA3
resume_from_checkpoint: True
```

Setting `resume_from_checkpoint: False` is picking the right checkpoint but it restarts from epoch 0.

```
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/torchtune/llama_guard_3_8B/full/epoch_4/
  checkpoint_files: [
    model-00001-of-00004.safetensors,
    model-00002-of-00004.safetensors,
    model-00003-of-00004.safetensors,
    model-00004-of-00004.safetensors
  ]
  recipe_checkpoint: /tmp/torchtune/llama_guard_3_8B/full/recipe_state/recipe_state.pt
  output_dir: ${output_dir}
  model_type: LLAMA3
resume_from_checkpoint: False
```

Could you please give any pointers on what should be the correct config?

**Comment by felipemello1** [comment]
hey @agunapal , we are working to make it more intuitive, but here are the docs: https://pytorch.org/torchtune/main/deep_dives/checkpointer.html#resuming-from-checkpoint-full-finetuning

you have to only change resume_from_checkpoint=Tre and checkpoint_files

**Comment by felipemello1** [comment]
Please reopen the issue if it still doesnt work for you

**Comment by subramen** [comment]
@felipemello1  having similar issues with resuming training, the output directory and checkpoint directory seem to be conflated in Checkpointer. I'm running the nightly 0.6.0. Following your instructions throws the error, seems like it is checking for these paths?

`TypeError: FullModelHFCheckpointer.__init__() missing 2 required positional arguments: 'checkpoint_dir' and 'output_dir'`

My understanding is:
`checkpoint_dir`: should be the output_dir of the previously trained model. This path will contain `base_model`, `epoch_N`, `recipe_state`.
`output_dir`: should be a separate dir

Issues:
* Checkpointer should be looking for recipe state and checkpoint files in `checkpoint_dir`, but it is instead looking in `output_dir` and failing.  
 
* Checkpointer looks for `checkpoint_dr/config.json` but it should be looking for `checkpoint_dir/base_model/config.json` **So i updated **

My workarounds to make it work:

```
cp -R checkpoint_dir/recipe_state output_dir
cp -R checkpoint_dir/epoch_N output_dir
checkpoint_dir = checkpoint_dir / base_model
```

**Comment by felipemello1** [comment]
hey @subramen , the docs only show what should be changed.

so if you have this
```
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Llama-3.2-1B-Instruct/
  checkpoint_files: [
    model.safetensors
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA3_2
resume_from_checkpoint: False
```

Now it will become this:
```
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Llama-3.2-1B-Instruct/
  checkpoint_files: [
    epoch_0/model.safetensors # <------ changed 
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA3_2
resume_from_checkpoint: True # <------  changed
```
