### ISSUE TITLE
Triton/Inductor shared memory issues with newer pytorch versions

### ISSUE THREAD

**Issue by nathan-az** [pytorch/torchtune#2572]
## Working Repro (2.7.0 nightly)

**Hardware:** AWS g6e.12xlarge (4x nvidia L40S, 40GB VRAM each, 384GB system RAM)

**Container:**
```
docker run -dit \
  --gpus all \
  --shm-size=100g \
  -v "$(pwd)/shared:/workspace" \
  ghcr.io/pytorch/pytorch-nightly:2.7.0.dev20250312-cuda11.8-cudnn9-devel
```
Note the absurdly large shm size, and use of an older 2.7.0 nightly.

**Train script (working):**

<details>

```sh
#!/bin/bash

export MLFLOW_TRACKING_URI=http://172.17.0.1:5000

# Check if git is installed, if not install it
if ! command -v git &> /dev/null; then
    echo "Git not found. Installing git..."
    apt update && apt install -yq git
fi


# pip uninstall -y torchvision torchaudio # to silence errors
# pip install --pre --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118
pip install --pre torchao --index-url https://download.pytorch.org/whl/nightly/cu118
pip install mlflow transformers hf-transfer
pip install -e ./torchtune

tune download meta-llama/Meta-Llama-3.1-8B-Instruct --output-dir inputs/model --ignore-patterns "original/consolidated.00.pth"

tune run \
    --nproc_per_node 4 \
    full_finetune_distributed \
    --config config.yaml \
    max_steps_per_epoch=20
```

</details>

Note in the train script that I comment out

```
# pip uninstall -y torchvision torchaudio # to silence errors
# pip install --pre --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118
```

## Broken Repro (latest 2.8.0 nightly)

Take the above train script and uncomment the reinstall of torch using nightlies. 

```
pytorch-triton==3.3.0+git96316ce5
torch==2.8.0.dev20250407+cu118
torchao==0.11.0.dev20250404+cu118
```
(Note that this same `torchao` version would be used in the above case too).

## Error

<details>

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/torchtune/recipes/full_finetune_distributed.py", line 955, in <module>
[rank0]:     sys.exit(recipe_main())
[rank0]:              ^^^^^^^^^^^^^
[rank0]:   File "/workspace/torchtune/torchtune/config/_parse.py", line 99, in wrapper
[rank0]:     sys.exit(recipe_main(conf))
[rank0]:              ^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/torchtune/recipes/full_finetune_distributed.py", line 950, in recipe_main
[rank0]:     recipe.train()
[rank0]:   File "/workspace/torchtune/recipes/full_finetune_distributed.py", line 821, in train
[rank0]:     current_loss.backward()
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_tensor.py", line 648, in backward
[rank0]:     torch.autograd.backward(
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/autograd/__init__.py", line 353, in backward
[rank0]:     _engine_run_backward(
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/autograd/graph.py", line 824, in _engine_run_backward
[rank0]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/autograd/function.py", line 307, in apply
[rank0]:     return user_fn(self, *args)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 2154, in backward
[rank0]:     return impl_fn()
[rank0]:            ^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 2140, in impl_fn
[rank0]:     out = CompiledFunction._backward_impl(ctx, all_args)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 2234, in _backward_impl
[rank0]:     CompiledFunction.compiled_bw = aot_config.bw_compiler(
[rank0]:                                    ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 483, in __call__
[rank0]:     return self.compiler_fn(gm, example_inputs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/backends/common.py", line 73, in _wrapped_bw_compiler
[rank0]:     disable(
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 850, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_utils_internal.py", line 97, in wrapper_function
[rank0]:     return function(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 2094, in bw_compiler
[rank0]:     return inner_compile(
[rank0]:            ^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 633, in compile_fx_inner
[rank0]:     return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/repro/after_aot.py", line 124, in debug_wrapper
[rank0]:     inner_compiled_fn = compiler_fn(gm, example_inputs)
[rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 743, in _compile_fx_inner
[rank0]:     mb_compiled_graph = fx_codegen_and_compile(
[rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1357, in fx_codegen_and_compile
[rank0]:     return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1246, in codegen_and_compile
[rank0]:     compiled_module = graph.compile_to_module()
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/graph.py", line 2201, in compile_to_module
[rank0]:     return self._compile_to_module()
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/graph.py", line 2248, in _compile_to_module
[rank0]:     mod = PyCodeCache.load_by_key_path(
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 2889, in load_by_key_path
[rank0]:     mod = _reload_python_module(key, path, set_sys_modules=in_toplevel)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/runtime/compile_tasks.py", line 31, in _reload_python_module
[rank0]:     exec(code, mod.__dict__, mod.__dict__)
[rank0]:   File "/tmp/torchinductor_root/l2/cl2zhotcxhpzdaft6me7tgibsemz2mg2bzqkpn6zbo7hu2ljjrwf.py", line 961, in <module>
[rank0]:     async_compile.wait(globals())
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/async_compile.py", line 446, in wait
[rank0]:     self._wait_futures(scope)
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/async_compile.py", line 466, in _wait_futures
[rank0]:     scope[key] = result.result()
[rank0]:                  ^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 3391, in result
[rank0]:     return self.result_fn()
[rank0]:            ^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/async_compile.py", line 341, in get_result
[rank0]:     kernel.precompile(
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 323, in precompile
[rank0]:     self._make_launchers()
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 485, in _make_launchers
[rank0]:     raise RuntimeError(f"No valid triton configs. {type(exc).__name__}: {exc}")
[rank0]: RuntimeError: No valid triton configs. OutOfResources: out of resource: shared memory, Required: 102144, Hardware limit: 101376. Reducing block sizes or `num_stages` may help.
```

</details>

I have omitted non-zero ranks for convenience. Note the OutOfResources error on shared memory (hence me trying with very large shm-size, although perhaps this is referring to a different type of shared memory?)

## Config

<details>

```yaml
output_dir: outputs

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: inputs/model/original/tokenizer.model
  max_seq_len: 1024

# Dataset
dataset:
  _component_: torchtune.datasets.alpaca_dataset
  packed: True  # True increases speed
seed: null
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.llama3_1.llama3_1_8b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: inputs/model
  checkpoint_files:
    filename_format: model-{}-of-{}.safetensors
    max_filename: "00004"
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA3
resume_from_checkpoint: False

# Parallelism tweaks
tensor_parallel_dim: 1 # 8-way TP
tensor_parallel_plan:
  _component_: torchtune.models.llama3.base_llama_tp_plan
data_parallel_shard_dim: 4 # -1 means to infer based on other parallel dims & world size
data_parallel_replicate_dim: 1

# Fine-tuning arguments
batch_size: 1
epochs: 1

optimizer:
  _component_: torch.optim.AdamW
  fused: True
  # _component_: torchao.prototype.low_bit_optim.AdamW8bit
  lr: 5.0e-05

loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
max_steps_per_epoch: null
gradient_accumulation_steps: 1  # Use to increase effective batch size

# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True  # True reduces memory
enable_activation_offloading: True  # True reduces memory
custom_sharded_layers: []  # Layers to shard separately (useful for large vocab size models). Lower Memory, but lower speed.
fsdp_cpu_offload: False
clip_grad_norm: null
compile: True  # torch.compile the model + loss, True increases speed + decreases memory
optimizer_in_bwd: False  # True saves memory. Requires gradient_accumulation_steps=1

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.MLFlowLogger
  experiment_name: 8b_testing
  run_name: default_latest
log_every_n_steps: 1
log_peak_memory_stats: True
```

</details>
