### ISSUE TITLE
Is there a plan to support Qwen2_5 DPO (full or LoRA)?

### ISSUE THREAD

**Issue by iqiancheng** [pytorch/torchtune#2630]

**Comment by SalmanMohammadi** [comment]
Hi @iqiancheng - this should just work out of the box. Which Qwen model are you interested in using? You'll just need to update an existing configuration for the model you're interested in - here's an example config for Qwen2.5 3B for the `full_dpo_distributed` recipe:

```yaml
# save this file as qwen_config.yaml
# tune download Qwen/Qwen2.5-3B-Instruct --output-dir /tmp/Qwen2.5-3B-Instruct
# tune run --nnodes 1 --nproc_per_node 4 full_dpo_distributed --config qwen_config.yaml
output_dir: /tmp/torchtune/qwen2_5_3B/full_dpo # /tmp may be deleted by your system. Change it to your preference.

# Model Arguments
model:
  _component_: torchtune.models.qwen2_5.qwen2_5_3b

# Tokenizer
tokenizer:
  _component_: torchtune.models.qwen2_5.qwen2_5_tokenizer
  path: /tmp/Qwen2.5-3B-Instruct/vocab.json
  merges_file: /tmp/Qwen2.5-3B-Instruct/merges.txt
  max_seq_len: null

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Qwen2.5-3B-Instruct
  checkpoint_files: [
    model-00001-of-00002.safetensors,
    model-00002-of-00002.safetensors,
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: QWEN2
resume_from_checkpoint: False

# The ref_checkpointer should always point to the original weights.
ref_checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Qwen2.5-3B-Instruct
  checkpoint_files: [
    model-00001-of-00002.safetensors,
    model-00002-of-00002.safetensors,
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: QWEN2

# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.stack_exchange_paired_dataset
seed: null
shuffle: True
batch_size: 4

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  fused: True
  weight_decay: 0.05
  lr: 2e-5
lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 20

loss:
  _component_: torchtune.rlhf.loss.DPOLoss
  beta: 0.05
  label_smoothing: 0

# Training
epochs: 1
max_steps_per_epoch: 1000
gradient_accumulation_steps: 8  # Use to increase effective batch size
compile: False  # torch.compile the model + loss, True increases speed + decreases memory

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}/logs
log_every_n_steps: 1
log_peak_memory_stats: True

# Environment
device: cuda
dtype: bf16

# Memory management
enable_activation_checkpointing: True  # True reduces memory
enable_activation_offloading: False  # True reduces memory
```

To create this config, I had to make the following changes:
- Change `model._component_` and `tokenizer._component_` to point to the new model I wanted to use, and the tokenizer for that model, respectively. All models in a model family will usually share the same tokenizer. 
- Update `checkpointer.checkpoint_dir`, `checkpointer.checkpoint_files`, and `checkpointer.model_type` to point to the location I've downloaded the model to, the model weights, and the model type. I just copied these sections from an [existing Qwen2.5 3B config](https://github.com/pytorch/torchtune/blob/main/recipes/configs/qwen2_5/3B_full_single_device.yaml). You'll want to make the corresponding changes to `ref_checkpointer` since this is a config for a full-finetuning DPO recipe.
- Finally, update `tokenizer.path` and `tokenizer.merges_file` to point to the downloaded Qwen2.5 tokenizer files - again, I just copied this from another config.

I hope this is helpful, please let me know how you get on : )
