### ISSUE TITLE
TP + Activation Offloading + Compile - different recomputed metadata error

### ISSUE THREAD

**Issue by nathan-az** [pytorch/torchtune#2684]
<details>

```
[rank1]: Traceback (most recent call last):
[rank1]:   File "/workspace/torchtune/recipes/full_finetune_distributed.py", line 1072, in <module>
[rank1]:     sys.exit(recipe_main())
[rank1]:              ^^^^^^^^^^^^^
[rank1]:   File "/workspace/torchtune/torchtune/config/_parse.py", line 99, in wrapper
[rank1]:     sys.exit(recipe_main(conf))
[rank1]:              ^^^^^^^^^^^^^^^^^
[rank1]:   File "/workspace/torchtune/recipes/full_finetune_distributed.py", line 1067, in recipe_main
[rank1]:     recipe.train()
[rank1]:   File "/workspace/torchtune/recipes/full_finetune_distributed.py", line 916, in train
[rank1]:     current_loss.backward()
[rank1]:   File "/opt/conda/lib/python3.11/site-packages/torch/_tensor.py", line 648, in backward
[rank1]:     torch.autograd.backward(
[rank1]:   File "/opt/conda/lib/python3.11/site-packages/torch/autograd/__init__.py", line 354, in backward
[rank1]:     _engine_run_backward(
[rank1]:   File "/opt/conda/lib/python3.11/site-packages/torch/autograd/graph.py", line 824, in _engine_run_backward
[rank1]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/opt/conda/lib/python3.11/site-packages/torch/autograd/function.py", line 307, in apply
[rank1]:     return user_fn(self, *args)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 2130, in backward
[rank1]:     ctx.saved_tensors,
[rank1]:     ^^^^^^^^^^^^^^^^^
[rank1]:   File "/opt/conda/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 1128, in unpack_hook
[rank1]:     frame.check_recomputed_tensors_match(gid)
[rank1]:   File "/opt/conda/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 902, in check_recomputed_tensors_match
[rank1]:     raise CheckpointError(
[rank1]: torch.utils.checkpoint.CheckpointError: torch.utils.checkpoint: Recomputed values for the following tensors have different metadata than during the forward pass.
[rank1]: tensor at position 0:
[rank1]: saved metadata: {'shape': torch.Size([4096]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=1)}
[rank1]: recomputed metadata: {'shape': torch.Size([1, 256, 4096]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=1)}
[rank1]: tensor at position 1:
[rank1]: saved metadata: {'shape': torch.Size([1, 256, 4096]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=1)}
[rank1]: recomputed metadata: {'shape': torch.Size([4096]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=1)}
```

</details>

The above error should be reproducible in `main` with the following (or similar) TP config (you may wish to change paths and metric logger):

<details>

```yaml
log_level: INFO
batch_size: 1
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_files:
    filename_format: model-{}-of-{}.safetensors
    max_filename: '00004'
  model_type: LLAMA3
  output_dir: ${output_dir}
  recipe_checkpoint: null
  checkpoint_dir: inputs/model
clip_grad_norm: null
compile: true
custom_sharded_layers: []

data_parallel_shard_dim: 1
data_parallel_replicate_dim: 1
tensor_parallel_dim: 4

enable_fp8_training: false
tensor_parallel_plan:
  _component_: torchtune.models.llama3.base_llama_tp_plan

dataset:
  _component_: torchtune.datasets.alpaca_dataset
  packed: True  # True increases speed
  train_on_input: true
device: cuda
dtype: bf16
enable_activation_checkpointing: true
enable_activation_offloading: true
epochs: 1
fsdp_cpu_offload: false
gradient_accumulation_steps: 2
log_every_n_steps: 1
log_peak_memory_stats: true
loss:
  _component_: torch.nn.CrossEntropyLoss
  reduction: mean
max_steps_per_epoch: 2

metric_logger:
  _component_: torchtune.training.metric_logging.MLFlowLogger
  experiment_name: optimisation_benchmarks
  run_name: base_tp_no_opt

optimizer:
  _component_: torchao.optim.AdamW8bit
  lr: 4.0e-05
optimizer_in_bwd: false
output_dir: outputs
resume_from_checkpoint: false
seed: 100
shuffle: true
tokenizer:
  max_seq_len: 1024
  path: inputs/model/original/tokenizer.model
  _component_: torchtune.models.llama3.llama3_tokenizer
model:
  _component_: torchtune.models.llama3_1.llama3_1_8b
```

</details>
