### ISSUE TITLE
Passing configurations in HF datasets?

### ISSUE THREAD

**Issue by virobles** [pytorch/torchtune#2729]
I got finetuning working perfectly with the `torchtune.datasets.alpaca_cleaned_dataset` but when trying to finetune on the [OpenCoder-LLM SFT-1](https://huggingface.co/datasets/OpenCoder-LLM/opc-sft-stage1) dataset I get the following error:
```bash
ValueError: Config name is missing.
Please pick one among the available configs: ['filtered_infinity_instruct', 'largescale_diverse_instruct', 'realuser_instruct']
```
Based on the [datasets documentation](https://huggingface.co/docs/datasets/v1.12.0/load_hub.html#select-a-configuration) I just need to pass one of those available configs to the `load_dataset` function, simple enough.

Documentation for [torchtune.datasets.instruct_dataset](https://docs.pytorch.org/torchtune/stable/generated/torchtune.datasets.instruct_dataset.html#torchtune.datasets.instruct_dataset) shows I can do it via  `**load_dataset_kwargs` but I don't know how to send those args via my config file.

Snippet:
```yaml
dataset:
  _component_: torchtune.datasets.instruct_dataset
  packed: False  # True increases speed
  column_map:
    input: instruction
    output: output
  source: OpenCoder-LLM/opc-sft-stage1
  train_on_input: false
  trust_remote_code: true
```

Any help is appreciated!

**Comment by joecummings** [comment]
Hiya! Looks like you should be able to just pass in using the `name` param:

```yaml
dataset:
  _component_: torchtune.datasets.instruct_dataset
  packed: False  # True increases speed
  train_on_input: false
  column_map:
    input: instruction
    output: output
  source: OpenCoder-LLM/opc-sft-stage1
  name: filtered_infinity_instruct
  trust_remote_code: true
```
