### ISSUE TITLE
Evaluate QWen3

### ISSUE THREAD

**Issue by step404** [pytorch/torchtune#2829]
I fine-turn QWen3 using config like this:

```
model:
  _component_: torchtune.models.qwen3.lora_qwen3_0_6b_instruct
  lora_attn_modules: ['q_proj', 'v_proj', 'output_proj']
  apply_lora_to_mlp: True
  lora_rank: 32  # higher increases accuracy and memory
  lora_alpha: 64  # usually alpha=2*rank
  lora_dropout: 0.0

tokenizer:
  _component_: torchtune.models.qwen3.qwen3_tokenizer
  path: /qwen0.6B/vocab.json
  merges_file: qwen0.6B/merges.txt
  max_seq_len: null

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /qwen0.6B
  checkpoint_files: [model.safetensors]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: QWEN3
resume_from_checkpoint: False
```
The artifacts produced by torchtune like this:

```
.
├── epoch_0
│   ├── adapter_config.json
│   ├── adapter_model.pt
│   ├── adapter_model.safetensors
│   ├── config.json
│   ├── generation_config.json
│   ├── merges.txt
│   ├── model-00001-of-00001.safetensors
│   ├── model.safetensors.index.json
│   ├── original_repo_id.json
│   ├── README.md
│   ├── tokenizer_config.json
│   ├── tokenizer.json
│   └── vocab.json
├── epoch_1
│   ├── adapter_config.json
│   ├── adapter_model.pt
│   ├── adapter_model.safetensors
│   ├── config.json
│   ├── generation_config.json
│   ├── merges.txt
│   ├── model-00001-of-00001.safetensors
│   ├── model.safetensors.index.json
│   ├── original_repo_id.json
│   ├── README.md
│   ├── tokenizer_config.json
│   ├── tokenizer.json
│   └── vocab.json
├── logs
│   └── log_1750044214.txt
├── recipe_state
│   └── recipe_state.pt
└── torchtune_config.yaml

4 directories, 29 files
```

I want to evaluate fine-tuned QWen3 model using torchtune, the evaluation config like this:
```
# Config for EleutherEvalRecipe in eleuther_eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune run eleuther_eval --config eleuther_evaluation tasks=["truthfulqa_mc2","hellaswag"]

output_dir: fineturn/

# Model Arguments
model:
  _component_: torchtune.models.qwen3.lora_qwen3_0_6b_instruct
  lora_attn_modules:
  - q_proj
  - v_proj
  - output_proj
  apply_lora_to_mlp: true
  lora_rank: 32
  lora_alpha: 64
  lora_dropout: 0.0

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: epoch_1/
  checkpoint_files: [
    model-00001-of-00001.safetensors,
    adapter_model.safetensors
  ] # [model-00001-of-00001.safetensors] or [model-00001-of-00001.safetensors, adapter_model.safetensors.pt] do not work.
  adapter_checkpoint: /adapter_model.safetensors #  /adapter_model.pt or deleting it do not work
  output_dir: ${output_dir}
  model_type: QWEN3
  recipe_checkpoint: fineturn/recipe_state/recipe_state.pt
  should_load_recipe_state: true

# Tokenizer
tokenizer:
  _component_: torchtune.models.qwen3.qwen3_tokenizer
  path: epoch_0/tokenizer.json
  merges_file: epoch_0/merges.txt
  max_seq_len: null

# Environment
device: cuda
dtype: bf16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed

# EleutherAI specific eval args
tasks: ["truthfulqa_mc2"]
limit: null
max_seq_length: 4096
batch_size: 8
enable_kv_cache: True

# Quantization specific args
quantizer: null
```
But I got an exception:

```
RuntimeError: Error(s) in loading state_dict for TransformerDecoder:
        Missing key(s) in state_dict: "layers.0.attn.q_proj.lora_a.weight", "layers.0.attn.q_proj.lora_b.weight", "layers.0.attn.v_proj.lora_a.weight"...
```
Is QWen3 supported? Or did I do something wrong?

**Comment by felipemello1** [comment]
hey @step404, good question!

tldr: Do this and it should work
```
# notice that we are not using the LoRa definition. We will use the merged weights
model:
  _component_: torchtune.models.qwen3.qwen3_0_6b_instruct

# just load the merged weights
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ${output_dir}/epoch_1/
  checkpoint_files: [
    model-00001-of-00001.safetensors, 
  ]
  output_dir: ${output_dir}
  model_type: QWEN3
```

You can also run it with vllm, which will be much faster and connect you to HF/vLLM directly. Check it here: https://docs.pytorch.org/torchtune/main/tutorials/e2e_flow.html#use-with-vllm


------

There are two issues:
1) The output trained model already has merged weights. **If you try to load the merged model + load the adapters, you will be running the adapters twice and this will be wrong**. So when running inference, you have to either:
a) Use the base untrained model + adapter
b) Just used the model with merged weights (this is what i am suggesting above)

2) You passed the wrong args, merging model weights + adapter. when it tried to load the adapter, it cannot find the layers in the error msg.
```
  checkpoint_files: [
    model-00001-of-00001.safetensors,
    adapter_model.safetensors
  ]
```

The adapter has its [own field](https://docs.pytorch.org/torchtune/main/deep_dives/checkpointer.html#resuming-from-checkpoint-lora-finetuning): 

```
checkpointer:
    # [... rest of the config...]
    adapter_checkpoint: epoch_{YOUR_EPOCH}/adapter_model.pt
```
