### ISSUE TITLE
Exception: Error converting the state dict. ; KeyError: 'tok_embeddings.weight'. 

### ISSUE THREAD

**Issue by adityaarun1** [pytorch/torchtune#917]
Hi,

I am following the tutorial to train Llama-3, and I have successfully fine-tuned the model on my custom dataset (that follows Alpaca dataset format). On running the generation script, I am getting the following error: `Exception: Error converting the state dict. Found unexpected key: "tok_embeddings.weight". Please make sure you're loading a checkpoint with the right format.` (Please check the screenshot attached). My generation script is as follows:
```
model:
  _component_: torchtune.models.llama3.llama3_8b

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: /workspace/out
  checkpoint_files: [
    /workspace/out/meta_model_0.pt
  ]
  output_dir: /workspace/out
  model_type: LLAMA3

device: cuda
dtype: bf16

seed: 1234

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /workspace/models/original/tokenizer.model

# Generation arguments; defaults taken from gpt-fast
prompt: "Hello, my name is"
max_new_tokens: 300
temperature: 0.6 
top_k: 300

quantizer: null
```

and I am running the following command: `tune run generate --config ./custom_generation_config.yaml`. Any ideas on what is going wrong?
